'use client';
import { createContext, useContext, useState, useEffect, useCallback } from 'react';

const TRANSLATIONS = {
  en: {
    /* ── Nav ── */
    training: 'Training', discover: 'Discover', report: 'Report', settings: 'Settings',
    trainingSub: 'Your personalized training hub',
    discoverSub: 'Explore workouts and exercises',
    reportSub: 'Track your fitness progress',
    settingsSub: 'App preferences and profile',

    /* ── Training screen ── */
    chooseBodyPart: 'Choose Body Part',
    chooseBodyPartSub: 'Select the muscle group to train today',
    chooseLevel: 'Choose Level',
    chooseLevelSub: 'Select your difficulty',
    chooseMode: 'Choose Mode',
    chooseModeSub: 'Where are you training today?',
    startWorkout: 'Start Workout',
    back: 'Back',
    skip: 'Skip',
    pause: 'Pause',
    resume: 'Resume',
    rest: 'Rest',
    complete: 'Complete',
    getReady: 'Get Ready',
    exercise: 'Exercise',
    exercises: 'exercises',
    nextExercise: 'Next Exercise',
    workoutComplete: 'Workout Complete!',
    totalCalories: 'Total Calories',
    totalReps: 'Total Reps',
    duration: 'Duration',
    done: 'Done',
    reps: 'reps',
    sec: 'sec',
    sets: 'sets',
    programs: 'Programs',
    selectProgram: 'Select a Program',
    /* Body parts */
    bp_full_body: 'Full Body', bp_full_body_sub: 'Total body strength & cardio',
    bp_chest: 'Chest', bp_chest_sub: 'Pecs, upper body push power',
    bp_arms: 'Arms', bp_arms_sub: 'Biceps, triceps & forearms',
    bp_legs: 'Legs', bp_legs_sub: 'Quads, hamstrings & glutes',
    bp_back: 'Back', bp_back_sub: 'Lats, traps & posterior chain',
    bp_abs: 'Abs', bp_abs_sub: 'Core strength & definition',
    /* Levels */
    beginner: 'Beginner', beginner_tag: 'Build your foundation',
    intermediate: 'Intermediate', intermediate_tag: 'Level up your game',
    advanced: 'Advanced', advanced_tag: 'Push your limits',
    /* Modes */
    mode_home: 'Home', mode_home_sub: 'Freehand & bodyweight',
    mode_home_desc: 'No equipment needed. Train anywhere with bodyweight movements.',
    mode_gym: 'Gym', mode_gym_sub: 'Weights & machines',
    mode_gym_desc: 'Full gym access. Barbells, dumbbells, cables & machines.',

    /* ── Discover screen ── */
    searchPlaceholder: 'Search workouts…',
    workoutType: 'Workout Type',
    close: 'Close',
    allCategories: 'All',
    filterLevel: 'Level',
    filterDuration: 'Duration',
    noResults: 'No results found',
    tryFilters: 'Try adjusting your filters',
    cantFind: "Can't find what you want?",
    tellUs: '✏️ Tell us what you need',
    results: 'results',
    result: 'result',
    min: 'min',
    startSession: 'Start Workout',
    exercises_label: 'Exercises',
    wt_muscle: 'Build Muscle', wt_warmup: 'Warm-Up', wt_fat: 'Fat Burning',
    wt_equipment: 'With Equipment', wt_stretching: 'Stretching', wt_cardio: 'Cardio',
    lvl_beginner: 'Beginner', lvl_intermediate: 'Intermediate', lvl_advanced: 'Advanced',
    history: 'History',
    weeklySummary: 'Weekly Summary',
    workoutsLabel: 'Workout',
    workoutsLabelP: 'Workouts',
    noWorkoutsYet: 'No workouts yet',
    noWorkoutsDesc: 'Complete a workout to see your history here.',
    picksForYou: 'Picks for you', startNow: 'Start Now ▶', forBeginners: 'For Beginners 🌱',
    challengesLabel: 'Challenges', stretchRecovery: 'Stretch & Recovery', stayActive: 'Stay active,\nstay in shape',

    /* ── Report screen ── */
    reportTitle: 'REPORT',
    statsWorkouts: 'Workouts',
    statsKcal: 'Kcal',
    statsMinutes: 'Minutes',
    allRecords: 'All records →',
    closeHistory: 'Close ✕',
    fullHistory: 'Full History',
    weeklyActivity: 'Weekly Activity',
    weeklyActivitySub: 'Calories burned per day this week',
    totalKcal: 'Total kcal',
    recentSessions: 'Recent Sessions',
    noSessionsYet: 'No sessions yet',
    noSessionsDesc: 'Complete a workout in the Training tab to see your history here',
    weightTracking: 'Weight Tracking',
    current: 'Current',
    vsFirst: 'vs first entry',
    logWeight: 'Log weight (kg)',
    log: 'Log',
    bmiCalculator: 'BMI Calculator',
    bmiSub: 'Body Mass Index',
    weightKg: 'WEIGHT (kg)',
    heightCm: 'HEIGHT (cm)',
    calcBmi: 'Calculate BMI',
    yourBmi: 'Your BMI Score',
    consistencyTitle: 'Consistency Analyzer',
    consistencySub: 'Check your dropout risk and get motivational insights',
    daysMissed: 'DAYS MISSED (this week)',
    consistencyScore: 'CONSISTENCY SCORE (0–100)',
    analyzeBtn: 'Analyze My Consistency',
    dropoutRisk: 'DROPOUT RISK',
    totalSessions: 'Total Sessions',
    keepGoing: 'Keep going!',
    exercisesDone: 'Exercises Done',
    totalCompleted: 'Total completed',
    today: 'Today',
    yesterday: 'Yesterday',
    daysAgo: 'days ago',
    quickSession: 'Quick session',

    /* ── Settings screen ── */
    preferences: 'Preferences',
    settingsTitle: 'Settings',
    freePlan: 'Free Plan · Edit Profile',
    upgradePremium: 'Upgrade to Premium',
    upgradeDesc: 'Unlock AI pose detection, custom plans & more',
    upgrade: 'Upgrade →',
    saveProfile: 'Save Profile',
    saved: '✅ Saved!',
    sectionWorkout: 'WORKOUT',
    sectionAudio: 'AUDIO & VOICE',
    sectionApp: 'APP',
    sectionData: 'DATA',
    restTime: 'Rest Time',
    restTimeSub: 'Seconds between sets',
    units: 'Units',
    unitsSub: 'Metric or Imperial',
    unitsMetric: 'Metric (kg/cm)',
    unitsImperial: 'Imperial (lb/in)',
    difficulty: 'Difficulty',
    difficultySub: 'Auto-adjust based on performance',
    soundEffects: 'Sound Effects',
    soundEffectsSub: 'Exercise cues and transitions',
    voiceCoach: 'Voice Coach',
    voiceCoachSub: 'Audio guidance during workouts',
    voiceCoachSpeaking: 'AI Coach speaking…',
    notifications: 'Notifications',
    notificationsSub: 'Workout reminders & streaks',
    language: 'Language',
    languageSub: 'Display language',
    darkMode: 'Dark Mode',
    darkModeSub: 'Enable dark theme',
    healthSync: 'Health Sync',
    healthSyncSub: 'Sync with Apple Health / Google Fit',
    backup: 'Backup & Restore',
    backupSub: 'Cloud sync your progress',
    backupBtn: 'Backup',
    clearData: 'Clear Data',
    clearDataSub: 'Delete all workout history',
    clearBtn: 'Clear',
    healthSyncMsg: 'Health Sync requires the FitAI mobile app.',
    healthSyncMsgDesc: 'Download the FitAI app on your iPhone or Android to sync with Apple Health or Google Fit automatically.',
    aiCoachHint: 'Click the 🤖 button anywhere to chat',
    name: 'Name', namePlaceholder: 'Your name',
    age: 'Age', agePlaceholder: 'e.g. 25',
    weightLabel: 'Weight (kg)', weightPlaceholder: 'e.g. 70',
    heightLabel: 'Height (cm)', heightPlaceholder: 'e.g. 175',
    appVersion: 'Version 1.0.0 · Made with ❤️',

    /* ── Challenge section ── */
    forTheBrave: 'For the brave',
    startBtn: 'START',
    dayLabel: 'DAY',
    pctFinished: '% Finished',
    aiRecommendation: 'AI Recommendation ✨',
    thisWeek: 'this week',
    continueWorkout: 'Continue Workout',
    discard: 'Discard',
    resumeBtn: 'Resume',
    noExercisesFound: 'No exercises found',
    exerciseOfLabel: 'Exercise',
    ofLabel: 'of',
    nextLabel: 'Next',
    finishLabel: 'Finish',
    skipRest: 'Skip Rest →',
    calories: 'Calories',
    completedLabel: 'Completed',
    timeLabel: 'Time',
    abs28Name: 'ABS CHALLENGE',
    abs28Desc: 'Daily core work to build visible abs in 4 weeks',
    abs28Short: '28 DAYS',
    fullbody30Name: 'FULL BODY',
    fullbody30Desc: 'Progressive full-body program from foundation to elite',
    fullbody30Short: '30 DAYS',
    fatburn14Name: 'FAT BURN',
    fatburn14Desc: 'Intense 2-week protocol for rapid fat loss',
    fatburn14Short: '14 DAYS',
    logoutBtn: 'Log Out',
    logoutSub: 'Sign out of your account',
    chatGreeting: "Hi! I'm your AI Fitness Coach 💪 Ask me about workouts, nutrition, or recovery!",
    chatPlaceholder: 'Ask anything…',
    chatOnline: 'Online',
    chatErrorMsg: "Couldn't connect. Please try again!",
    chatPrompt1: 'Build muscle faster?',
    chatPrompt2: 'Best fat loss exercises?',
    chatPrompt3: 'How many rest days?',
    chatPrompt4: 'Pre-workout nutrition?',
    chatPrompt5: 'Improve flexibility?',
    chatPrompt6: 'Weekly training plan',
  },

  es: {
    training: 'Entrenamiento', discover: 'Descubrir', report: 'Informe', settings: 'Ajustes',
    trainingSub: 'Tu centro de entrenamiento personalizado',
    discoverSub: 'Explora ejercicios y rutinas',
    reportSub: 'Sigue tu progreso físico',
    settingsSub: 'Preferencias y perfil',

    chooseBodyPart: 'Elige Grupo Muscular',
    chooseBodyPartSub: 'Selecciona el músculo a trabajar hoy',
    chooseLevel: 'Elige Nivel',
    chooseLevelSub: 'Selecciona tu dificultad',
    chooseMode: 'Elige Modo',
    chooseModeSub: '¿Dónde entrenas hoy?',
    startWorkout: 'Iniciar Entrenamiento',
    back: 'Atrás',
    skip: 'Saltar',
    pause: 'Pausar',
    resume: 'Reanudar',
    rest: 'Descanso',
    complete: 'Completar',
    getReady: 'Prepárate',
    exercise: 'Ejercicio',
    exercises: 'ejercicios',
    nextExercise: 'Siguiente Ejercicio',
    workoutComplete: '¡Entrenamiento Completo!',
    totalCalories: 'Calorías Totales',
    totalReps: 'Repeticiones Totales',
    duration: 'Duración',
    done: 'Listo',
    reps: 'reps',
    sec: 'seg',
    sets: 'series',
    programs: 'Programas',
    selectProgram: 'Seleccionar Programa',
    bp_full_body: 'Cuerpo Completo', bp_full_body_sub: 'Fuerza total y cardio',
    bp_chest: 'Pecho', bp_chest_sub: 'Pectorales, empuje de tren superior',
    bp_arms: 'Brazos', bp_arms_sub: 'Bíceps, tríceps y antebrazos',
    bp_legs: 'Piernas', bp_legs_sub: 'Cuádriceps, isquiotibiales y glúteos',
    bp_back: 'Espalda', bp_back_sub: 'Dorsales, trapecios y cadena posterior',
    bp_abs: 'Abdomen', bp_abs_sub: 'Fuerza y definición del core',
    beginner: 'Principiante', beginner_tag: 'Construye tu base',
    intermediate: 'Intermedio', intermediate_tag: 'Sube de nivel',
    advanced: 'Avanzado', advanced_tag: 'Supera tus límites',
    mode_home: 'Casa', mode_home_sub: 'Libre y peso corporal',
    mode_home_desc: 'Sin equipo. Entrena en cualquier lugar con movimientos de peso corporal.',
    mode_gym: 'Gimnasio', mode_gym_sub: 'Pesas y máquinas',
    mode_gym_desc: 'Acceso completo al gimnasio. Barras, mancuernas, cables y máquinas.',

    searchPlaceholder: 'Buscar entrenamientos…',
    workoutType: 'Tipo de Entrenamiento', close: 'Cerrar',
    allCategories: 'Todo',
    filterLevel: 'Nivel',
    filterDuration: 'Duración',
    noResults: 'Sin resultados',
    tryFilters: 'Intenta ajustar los filtros',
    cantFind: '¿No encuentras lo que buscas?',
    tellUs: '✏️ Dinos qué necesitas',
    results: 'resultados',
    result: 'resultado',
    min: 'min',
    startSession: 'Iniciar Entrenamiento',
    exercises_label: 'Ejercicios',
    wt_muscle: 'Ganar Músculo', wt_warmup: 'Calentamiento', wt_fat: 'Quemar Grasa',
    wt_equipment: 'Con Equipo', wt_stretching: 'Estiramiento', wt_cardio: 'Cardio',
    lvl_beginner: 'Principiante', lvl_intermediate: 'Intermedio', lvl_advanced: 'Avanzado',
    history: 'Historial',
    weeklySummary: 'Resumen Semanal',
    workoutsLabel: 'Entrenamiento',
    workoutsLabelP: 'Entrenamientos',
    noWorkoutsYet: 'Sin entrenamientos aún',
    noWorkoutsDesc: 'Completa un entrenamiento para ver tu historial aquí.',
    picksForYou: 'Para ti', startNow: 'Empezar ▶', forBeginners: 'Para Principiantes 🌱',
    challengesLabel: 'Desafíos', stretchRecovery: 'Estiramiento & Recuperación', stayActive: 'Mantente activo,\nmantente en forma',

    reportTitle: 'INFORME',
    statsWorkouts: 'Entrenamientos',
    statsKcal: 'Kcal',
    statsMinutes: 'Minutos',
    allRecords: 'Todos los registros →',
    closeHistory: 'Cerrar ✕',
    fullHistory: 'Historial Completo',
    weeklyActivity: 'Actividad Semanal',
    weeklyActivitySub: 'Calorías quemadas por día esta semana',
    totalKcal: 'Kcal totales',
    recentSessions: 'Sesiones Recientes',
    noSessionsYet: 'Sin sesiones aún',
    noSessionsDesc: 'Completa un entrenamiento en la pestaña Entrenamiento para ver tu historial aquí',
    weightTracking: 'Control de Peso',
    current: 'Actual',
    vsFirst: 'vs primera entrada',
    logWeight: 'Registrar peso (kg)',
    log: 'Registrar',
    bmiCalculator: 'Calculadora IMC',
    bmiSub: 'Índice de Masa Corporal',
    weightKg: 'PESO (kg)',
    heightCm: 'ALTURA (cm)',
    calcBmi: 'Calcular IMC',
    yourBmi: 'Tu Puntuación IMC',
    consistencyTitle: 'Analizador de Consistencia',
    consistencySub: 'Revisa tu riesgo de abandono y obtén motivación',
    daysMissed: 'DÍAS PERDIDOS (esta semana)',
    consistencyScore: 'PUNTUACIÓN DE CONSISTENCIA (0–100)',
    analyzeBtn: 'Analizar Mi Consistencia',
    dropoutRisk: 'RIESGO DE ABANDONO',
    totalSessions: 'Sesiones Totales',
    keepGoing: '¡Sigue adelante!',
    exercisesDone: 'Ejercicios Realizados',
    totalCompleted: 'Total completados',
    today: 'Hoy',
    yesterday: 'Ayer',
    daysAgo: 'días atrás',
    quickSession: 'Sesión rápida',

    preferences: 'Preferencias',
    settingsTitle: 'Ajustes',
    freePlan: 'Plan Gratuito · Editar Perfil',
    upgradePremium: 'Hazte Premium',
    upgradeDesc: 'Desbloquea detección de pose IA, planes personalizados y más',
    upgrade: 'Mejorar →',
    saveProfile: 'Guardar Perfil',
    saved: '✅ ¡Guardado!',
    sectionWorkout: 'ENTRENAMIENTO',
    sectionAudio: 'AUDIO Y VOZ',
    sectionApp: 'APLICACIÓN',
    sectionData: 'DATOS',
    restTime: 'Tiempo de Descanso',
    restTimeSub: 'Segundos entre series',
    units: 'Unidades',
    unitsSub: 'Métrico o Imperial',
    unitsMetric: 'Métrico (kg/cm)',
    unitsImperial: 'Imperial (lb/in)',
    difficulty: 'Dificultad',
    difficultySub: 'Ajuste automático según rendimiento',
    soundEffects: 'Efectos de Sonido',
    soundEffectsSub: 'Señales de ejercicio y transiciones',
    voiceCoach: 'Entrenador de Voz',
    voiceCoachSub: 'Guía de audio durante los entrenamientos',
    voiceCoachSpeaking: 'Entrenador IA hablando…',
    notifications: 'Notificaciones',
    notificationsSub: 'Recordatorios y rachas de entrenamiento',
    language: 'Idioma',
    languageSub: 'Idioma de visualización',
    darkMode: 'Modo Oscuro',
    darkModeSub: 'Activar tema oscuro',
    healthSync: 'Sincronizar Salud',
    healthSyncSub: 'Sincronizar con Apple Health / Google Fit',
    backup: 'Copia de Seguridad',
    backupSub: 'Sincroniza tu progreso en la nube',
    backupBtn: 'Respaldar',
    clearData: 'Borrar Datos',
    clearDataSub: 'Eliminar todo el historial de entrenamientos',
    clearBtn: 'Borrar',
    healthSyncMsg: 'La sincronización de salud requiere la app móvil de FitAI.',
    healthSyncMsgDesc: 'Descarga la app FitAI en tu iPhone o Android para sincronizar con Apple Health o Google Fit.',
    aiCoachHint: 'Toca el botón 🤖 en cualquier lugar para chatear',
    name: 'Nombre', namePlaceholder: 'Tu nombre',
    age: 'Edad', agePlaceholder: 'ej. 25',
    weightLabel: 'Peso (kg)', weightPlaceholder: 'ej. 70',
    heightLabel: 'Altura (cm)', heightPlaceholder: 'ej. 175',
    appVersion: 'Versión 1.0.0 · Hecho con ❤️',

    forTheBrave: 'Para los valientes',
    startBtn: 'INICIAR',
    dayLabel: 'DÍA',
    pctFinished: '% Completado',
    aiRecommendation: 'Recomendación IA ✨',
    thisWeek: 'esta semana',
    continueWorkout: 'Continuar Entrenamiento',
    discard: 'Descartar',
    resumeBtn: 'Reanudar',
    noExercisesFound: 'No se encontraron ejercicios',
    exerciseOfLabel: 'Ejercicio',
    ofLabel: 'de',
    nextLabel: 'Siguiente',
    finishLabel: 'Finalizar',
    skipRest: 'Saltar Descanso →',
    calories: 'Calorías',
    completedLabel: 'Completado',
    timeLabel: 'Tiempo',
    abs28Name: 'DESAFÍO ABS',
    abs28Desc: 'Trabajo diario de core para definir abdominales en 4 semanas',
    abs28Short: '28 DÍAS',
    fullbody30Name: 'CUERPO COMPLETO',
    fullbody30Desc: 'Programa completo progresivo de la base a élite',
    fullbody30Short: '30 DÍAS',
    fatburn14Name: 'QUEMA GRASA',
    fatburn14Desc: 'Protocolo intenso de 2 semanas para pérdida rápida de grasa',
    fatburn14Short: '14 DÍAS',
    logoutBtn: 'Cerrar Sesión',
    logoutSub: 'Salir de tu cuenta',
    chatGreeting: '¡Hola! Soy tu Entrenador IA 💪 ¡Pregúntame sobre entrenamientos, nutrición o recuperación!',
    chatPlaceholder: 'Pregunta lo que quieras…',
    chatOnline: 'En línea',
    chatErrorMsg: 'No se pudo conectar. ¡Inténtalo de nuevo!',
    chatPrompt1: '¿Ganar músculo más rápido?',
    chatPrompt2: '¿Mejores ejercicios para quemar grasa?',
    chatPrompt3: '¿Cuántos días de descanso?',
    chatPrompt4: '¿Nutrición pre-entrenamiento?',
    chatPrompt5: '¿Mejorar flexibilidad?',
    chatPrompt6: 'Plan semanal de entrenamiento',
  },

  fr: {
    training: 'Entraînement', discover: 'Découvrir', report: 'Rapport', settings: 'Paramètres',
    trainingSub: 'Votre centre d\'entraînement personnalisé',
    discoverSub: 'Explorez exercices et séances',
    reportSub: 'Suivez votre progression',
    settingsSub: 'Préférences et profil',

    chooseBodyPart: 'Choisir le Groupe Musculaire',
    chooseBodyPartSub: 'Sélectionnez le muscle à entraîner aujourd\'hui',
    chooseLevel: 'Choisir le Niveau',
    chooseLevelSub: 'Sélectionnez votre difficulté',
    chooseMode: 'Choisir le Mode',
    chooseModeSub: 'Où vous entraînez-vous aujourd\'hui ?',
    startWorkout: 'Démarrer l\'Entraînement',
    back: 'Retour',
    skip: 'Passer',
    pause: 'Pause',
    resume: 'Reprendre',
    rest: 'Repos',
    complete: 'Terminer',
    getReady: 'Préparez-vous',
    exercise: 'Exercice',
    exercises: 'exercices',
    nextExercise: 'Exercice Suivant',
    workoutComplete: 'Entraînement Terminé !',
    totalCalories: 'Calories Totales',
    totalReps: 'Répétitions Totales',
    duration: 'Durée',
    done: 'Terminé',
    reps: 'rép',
    sec: 'sec',
    sets: 'séries',
    programs: 'Programmes',
    selectProgram: 'Sélectionner un Programme',
    bp_full_body: 'Corps Entier', bp_full_body_sub: 'Force totale et cardio',
    bp_chest: 'Poitrine', bp_chest_sub: 'Pectoraux, poussée du haut du corps',
    bp_arms: 'Bras', bp_arms_sub: 'Biceps, triceps et avant-bras',
    bp_legs: 'Jambes', bp_legs_sub: 'Quadriceps, ischio-jambiers et fessiers',
    bp_back: 'Dos', bp_back_sub: 'Dorsaux, trapèzes et chaîne postérieure',
    bp_abs: 'Abdominaux', bp_abs_sub: 'Force et définition du core',
    beginner: 'Débutant', beginner_tag: 'Construisez vos bases',
    intermediate: 'Intermédiaire', intermediate_tag: 'Passez au niveau supérieur',
    advanced: 'Avancé', advanced_tag: 'Repoussez vos limites',
    mode_home: 'Maison', mode_home_sub: 'Poids du corps libre',
    mode_home_desc: 'Sans équipement. Entraînez-vous partout avec des mouvements au poids du corps.',
    mode_gym: 'Salle', mode_gym_sub: 'Poids et machines',
    mode_gym_desc: 'Accès complet à la salle. Barres, haltères, câbles et machines.',

    searchPlaceholder: 'Rechercher des séances…',
    workoutType: 'Type d\'Entraînement', close: 'Fermer',
    allCategories: 'Tout',
    filterLevel: 'Niveau',
    filterDuration: 'Durée',
    noResults: 'Aucun résultat',
    tryFilters: 'Essayez d\'ajuster les filtres',
    cantFind: 'Vous ne trouvez pas ce que vous cherchez ?',
    tellUs: '✏️ Dites-nous ce dont vous avez besoin',
    results: 'résultats',
    result: 'résultat',
    min: 'min',
    startSession: 'Démarrer',
    exercises_label: 'Exercices',
    wt_muscle: 'Musculation', wt_warmup: 'Échauffement', wt_fat: 'Brûle-graisses',
    wt_equipment: 'Avec Équipement', wt_stretching: 'Étirements', wt_cardio: 'Cardio',
    lvl_beginner: 'Débutant', lvl_intermediate: 'Intermédiaire', lvl_advanced: 'Avancé',
    history: 'Historique',
    weeklySummary: 'Résumé Hebdomadaire',
    workoutsLabel: 'Séance',
    workoutsLabelP: 'Séances',
    noWorkoutsYet: 'Pas encore de séances',
    noWorkoutsDesc: 'Terminez un entraînement pour voir votre historique ici.',
    picksForYou: 'Sélectionnés pour vous', startNow: 'Commencer ▶', forBeginners: 'Pour Débutants 🌱',
    challengesLabel: 'Défis', stretchRecovery: 'Étirements & Récupération', stayActive: 'Reste actif,\nreste en forme',

    reportTitle: 'RAPPORT',
    statsWorkouts: 'Séances',
    statsKcal: 'Kcal',
    statsMinutes: 'Minutes',
    allRecords: 'Tous les enregistrements →',
    closeHistory: 'Fermer ✕',
    fullHistory: 'Historique Complet',
    weeklyActivity: 'Activité Hebdomadaire',
    weeklyActivitySub: 'Calories brûlées par jour cette semaine',
    totalKcal: 'Kcal totales',
    recentSessions: 'Séances Récentes',
    noSessionsYet: 'Aucune séance encore',
    noSessionsDesc: 'Terminez un entraînement dans l\'onglet Entraînement pour voir votre historique ici',
    weightTracking: 'Suivi du Poids',
    current: 'Actuel',
    vsFirst: 'vs première entrée',
    logWeight: 'Enregistrer le poids (kg)',
    log: 'Enregistrer',
    bmiCalculator: 'Calculateur IMC',
    bmiSub: 'Indice de Masse Corporelle',
    weightKg: 'POIDS (kg)',
    heightCm: 'TAILLE (cm)',
    calcBmi: 'Calculer l\'IMC',
    yourBmi: 'Votre Score IMC',
    consistencyTitle: 'Analyseur de Constance',
    consistencySub: 'Vérifiez votre risque d\'abandon et obtenez des conseils',
    daysMissed: 'JOURS MANQUÉS (cette semaine)',
    consistencyScore: 'SCORE DE CONSTANCE (0–100)',
    analyzeBtn: 'Analyser Ma Constance',
    dropoutRisk: 'RISQUE D\'ABANDON',
    totalSessions: 'Séances Totales',
    keepGoing: 'Continuez !',
    exercisesDone: 'Exercices Réalisés',
    totalCompleted: 'Total complétés',
    today: 'Aujourd\'hui',
    yesterday: 'Hier',
    daysAgo: 'jours passés',
    quickSession: 'Séance rapide',

    preferences: 'Préférences',
    settingsTitle: 'Paramètres',
    freePlan: 'Gratuit · Modifier le profil',
    upgradePremium: 'Passer au Premium',
    upgradeDesc: 'Débloquez la détection de pose IA, les plans personnalisés et plus',
    upgrade: 'Améliorer →',
    saveProfile: 'Enregistrer le Profil',
    saved: '✅ Enregistré !',
    sectionWorkout: 'ENTRAÎNEMENT',
    sectionAudio: 'AUDIO ET VOIX',
    sectionApp: 'APPLICATION',
    sectionData: 'DONNÉES',
    restTime: 'Temps de Repos',
    restTimeSub: 'Secondes entre les séries',
    units: 'Unités',
    unitsSub: 'Métrique ou Impérial',
    unitsMetric: 'Métrique (kg/cm)',
    unitsImperial: 'Impérial (lb/in)',
    difficulty: 'Difficulté',
    difficultySub: 'Ajustement automatique selon les performances',
    soundEffects: 'Effets Sonores',
    soundEffectsSub: 'Repères d\'exercice et transitions',
    voiceCoach: 'Coach Vocal',
    voiceCoachSub: 'Guidage audio pendant les séances',
    voiceCoachSpeaking: 'Entraîneur IA en train de parler…',
    notifications: 'Notifications',
    notificationsSub: 'Rappels et séries d\'entraînement',
    language: 'Langue',
    languageSub: 'Langue d\'affichage',
    darkMode: 'Mode Sombre',
    darkModeSub: 'Activer le thème sombre',
    healthSync: 'Sync. Santé',
    healthSyncSub: 'Synchroniser avec Apple Health / Google Fit',
    backup: 'Sauvegarde et Restauration',
    backupSub: 'Synchronisation cloud de vos progrès',
    backupBtn: 'Sauvegarder',
    clearData: 'Effacer les Données',
    clearDataSub: 'Supprimer tout l\'historique d\'entraînement',
    clearBtn: 'Effacer',
    healthSyncMsg: 'La synchronisation santé nécessite l\'app mobile FitAI.',
    healthSyncMsgDesc: 'Téléchargez l\'app FitAI sur iPhone ou Android pour synchroniser avec Apple Health ou Google Fit.',
    aiCoachHint: 'Cliquez sur 🤖 n\'importe où pour discuter',
    name: 'Nom', namePlaceholder: 'Votre nom',
    age: 'Âge', agePlaceholder: 'ex. 25',
    weightLabel: 'Poids (kg)', weightPlaceholder: 'ex. 70',
    heightLabel: 'Taille (cm)', heightPlaceholder: 'ex. 175',
    appVersion: 'Version 1.0.0 · Fait avec ❤️',

    forTheBrave: 'Pour les courageux',
    startBtn: 'DÉMARRER',
    dayLabel: 'JOUR',
    pctFinished: '% Terminé',
    aiRecommendation: 'Recommandation IA ✨',
    thisWeek: 'cette semaine',
    continueWorkout: 'Continuer l\'Entraînement',
    discard: 'Abandonner',
    resumeBtn: 'Reprendre',
    noExercisesFound: 'Aucun exercice trouvé',
    exerciseOfLabel: 'Exercice',
    ofLabel: 'sur',
    nextLabel: 'Suivant',
    finishLabel: 'Terminer',
    skipRest: 'Passer le repos →',
    calories: 'Calories',
    completedLabel: 'Terminé',
    timeLabel: 'Temps',
    abs28Name: 'DÉFI ABS',
    abs28Desc: 'Travail quotidien du core pour des abdos visibles en 4 semaines',
    abs28Short: '28 JOURS',
    fullbody30Name: 'CORPS ENTIER',
    fullbody30Desc: 'Programme progressif du corps entier, des bases à l\'élite',
    fullbody30Short: '30 JOURS',
    fatburn14Name: 'BRÛLE-GRAISSES',
    fatburn14Desc: 'Protocole intensif de 2 semaines pour une perte de graisse rapide',
    fatburn14Short: '14 JOURS',
    logoutBtn: 'Se Déconnecter',
    logoutSub: 'Quitter votre compte',
    chatGreeting: "Salut ! Je suis ton Coach IA 💪 Pose-moi des questions sur les entraînements, la nutrition ou la récupération !",
    chatPlaceholder: 'Demandez n\'importe quoi…',
    chatOnline: 'En ligne',
    chatErrorMsg: 'Impossible de se connecter. Réessayez !',
    chatPrompt1: 'Gagner du muscle plus vite ?',
    chatPrompt2: 'Meilleurs exercices brûle-graisses ?',
    chatPrompt3: 'Combien de jours de repos ?',
    chatPrompt4: 'Nutrition avant l\'entraînement ?',
    chatPrompt5: 'Améliorer la flexibilité ?',
    chatPrompt6: 'Plan d\'entraînement hebdomadaire',
  },

  de: {
    training: 'Training', discover: 'Entdecken', report: 'Bericht', settings: 'Einstellungen',
    trainingSub: 'Dein persönliches Trainingszentrum',
    discoverSub: 'Übungen und Workouts entdecken',
    reportSub: 'Deinen Fortschritt verfolgen',
    settingsSub: 'App-Einstellungen und Profil',

    chooseBodyPart: 'Muskelgruppe wählen',
    chooseBodyPartSub: 'Wähle die Muskelgruppe für heute',
    chooseLevel: 'Level wählen',
    chooseLevelSub: 'Wähle deinen Schwierigkeitsgrad',
    chooseMode: 'Modus wählen',
    chooseModeSub: 'Wo trainierst du heute?',
    startWorkout: 'Training starten',
    back: 'Zurück',
    skip: 'Überspringen',
    pause: 'Pause',
    resume: 'Fortsetzen',
    rest: 'Pause',
    complete: 'Abschließen',
    getReady: 'Mach dich bereit',
    exercise: 'Übung',
    exercises: 'Übungen',
    nextExercise: 'Nächste Übung',
    workoutComplete: 'Training Abgeschlossen!',
    totalCalories: 'Gesamtkalorien',
    totalReps: 'Gesamtwiederholungen',
    duration: 'Dauer',
    done: 'Fertig',
    reps: 'Whd.',
    sec: 'Sek.',
    sets: 'Sätze',
    programs: 'Programme',
    selectProgram: 'Programm auswählen',
    bp_full_body: 'Ganzkörper', bp_full_body_sub: 'Ganzkörperkraft und Cardio',
    bp_chest: 'Brust', bp_chest_sub: 'Brustmuskeln, Oberkörper-Druckübungen',
    bp_arms: 'Arme', bp_arms_sub: 'Bizeps, Trizeps und Unterarme',
    bp_legs: 'Beine', bp_legs_sub: 'Quadrizeps, Oberschenkel und Gesäß',
    bp_back: 'Rücken', bp_back_sub: 'Latissimus, Fallen und hintere Kette',
    bp_abs: 'Bauch', bp_abs_sub: 'Core-Stärke und Definition',
    beginner: 'Anfänger', beginner_tag: 'Baue dein Fundament',
    intermediate: 'Mittelstufe', intermediate_tag: 'Steigere dein Spiel',
    advanced: 'Fortgeschritten', advanced_tag: 'Gehe an deine Grenzen',
    mode_home: 'Zuhause', mode_home_sub: 'Freihand & Körpergewicht',
    mode_home_desc: 'Kein Equipment nötig. Trainiere überall mit Körpergewichtsübungen.',
    mode_gym: 'Fitnessstudio', mode_gym_sub: 'Gewichte & Maschinen',
    mode_gym_desc: 'Voller Zugang zum Gym. Langhanteln, Kurzhanteln, Kabel & Maschinen.',

    searchPlaceholder: 'Workouts suchen…',
    workoutType: 'Trainingsart', close: 'Schließen',
    allCategories: 'Alle',
    filterLevel: 'Level',
    filterDuration: 'Dauer',
    noResults: 'Keine Ergebnisse',
    tryFilters: 'Versuche, die Filter anzupassen',
    cantFind: 'Nicht gefunden, was du suchst?',
    tellUs: '✏️ Sag uns, was du brauchst',
    results: 'Ergebnisse',
    result: 'Ergebnis',
    min: 'Min.',
    startSession: 'Training starten',
    exercises_label: 'Übungen',
    wt_muscle: 'Muskelaufbau', wt_warmup: 'Aufwärmen', wt_fat: 'Fettverbrennung',
    wt_equipment: 'Mit Geräten', wt_stretching: 'Dehnen', wt_cardio: 'Cardio',
    lvl_beginner: 'Anfänger', lvl_intermediate: 'Mittelstufe', lvl_advanced: 'Fortgeschritten',
    history: 'Verlauf',
    weeklySummary: 'Wöchentliche Zusammenfassung',
    workoutsLabel: 'Training',
    workoutsLabelP: 'Trainings',
    noWorkoutsYet: 'Noch keine Trainings',
    noWorkoutsDesc: 'Schließe ein Training ab, um deinen Verlauf hier zu sehen.',
    picksForYou: 'Für dich', startNow: 'Starten ▶', forBeginners: 'Für Anfänger 🌱',
    challengesLabel: 'Challenges', stretchRecovery: 'Dehnen & Erholung', stayActive: 'Bleib aktiv,\nbleib in Form',

    reportTitle: 'BERICHT',
    statsWorkouts: 'Trainings',
    statsKcal: 'Kcal',
    statsMinutes: 'Minuten',
    allRecords: 'Alle Einträge →',
    closeHistory: 'Schließen ✕',
    fullHistory: 'Vollständiger Verlauf',
    weeklyActivity: 'Wöchentliche Aktivität',
    weeklyActivitySub: 'Kalorien pro Tag diese Woche',
    totalKcal: 'Kcal gesamt',
    recentSessions: 'Letzte Einheiten',
    noSessionsYet: 'Noch keine Einheiten',
    noSessionsDesc: 'Schließe ein Training im Training-Tab ab, um deinen Verlauf zu sehen',
    weightTracking: 'Gewichtsverfolgung',
    current: 'Aktuell',
    vsFirst: 'vs. erster Eintrag',
    logWeight: 'Gewicht eingeben (kg)',
    log: 'Eintragen',
    bmiCalculator: 'BMI-Rechner',
    bmiSub: 'Body-Mass-Index',
    weightKg: 'GEWICHT (kg)',
    heightCm: 'GRÖSSE (cm)',
    calcBmi: 'BMI berechnen',
    yourBmi: 'Dein BMI-Wert',
    consistencyTitle: 'Konsistenz-Analyse',
    consistencySub: 'Prüfe dein Abbruchrisiko und erhalte Motivation',
    daysMissed: 'VERPASSTE TAGE (diese Woche)',
    consistencyScore: 'KONSISTENZ-WERT (0–100)',
    analyzeBtn: 'Meine Konsistenz analysieren',
    dropoutRisk: 'ABBRUCHRISIKO',
    totalSessions: 'Einheiten gesamt',
    keepGoing: 'Weiter so!',
    exercisesDone: 'Übungen gemacht',
    totalCompleted: 'Gesamt abgeschlossen',
    today: 'Heute',
    yesterday: 'Gestern',
    daysAgo: 'Tage her',
    quickSession: 'Kurze Einheit',

    preferences: 'Einstellungen',
    settingsTitle: 'Einstellungen',
    freePlan: 'Kostenlos · Profil bearbeiten',
    upgradePremium: 'Premium kaufen',
    upgradeDesc: 'KI-Pose-Erkennung, individuelle Pläne & mehr freischalten',
    upgrade: 'Upgrade →',
    saveProfile: 'Profil speichern',
    saved: '✅ Gespeichert!',
    sectionWorkout: 'TRAINING',
    sectionAudio: 'AUDIO & STIMME',
    sectionApp: 'APP',
    sectionData: 'DATEN',
    restTime: 'Pausenzeit',
    restTimeSub: 'Sekunden zwischen den Sätzen',
    units: 'Einheiten',
    unitsSub: 'Metrisch oder Imperial',
    unitsMetric: 'Metrisch (kg/cm)',
    unitsImperial: 'Imperial (lb/in)',
    difficulty: 'Schwierigkeit',
    difficultySub: 'Automatische Anpassung an die Leistung',
    soundEffects: 'Soundeffekte',
    soundEffectsSub: 'Übungssignale und Übergänge',
    voiceCoach: 'Sprach-Coach',
    voiceCoachSub: 'Audio-Anleitung während des Trainings',
    voiceCoachSpeaking: 'KI-Coach spricht…',
    notifications: 'Benachrichtigungen',
    notificationsSub: 'Trainingserinnerungen & Streaks',
    language: 'Sprache',
    languageSub: 'Anzeigesprache',
    darkMode: 'Dunkelmodus',
    darkModeSub: 'Dunkles Thema aktivieren',
    healthSync: 'Gesundheitssync',
    healthSyncSub: 'Mit Apple Health / Google Fit synchronisieren',
    backup: 'Backup & Wiederherstellung',
    backupSub: 'Cloud-Synchronisierung deines Fortschritts',
    backupBtn: 'Backup',
    clearData: 'Daten löschen',
    clearDataSub: 'Gesamten Trainingsverlauf löschen',
    clearBtn: 'Löschen',
    healthSyncMsg: 'Gesundheitssync erfordert die FitAI-App.',
    healthSyncMsgDesc: 'Lade die FitAI-App auf dein iPhone oder Android herunter, um sie mit Apple Health oder Google Fit zu synchronisieren.',
    aiCoachHint: 'Klicke auf den 🤖 Button um zu chatten',
    name: 'Name', namePlaceholder: 'Dein Name',
    age: 'Alter', agePlaceholder: 'z.B. 25',
    weightLabel: 'Gewicht (kg)', weightPlaceholder: 'z.B. 70',
    heightLabel: 'Größe (cm)', heightPlaceholder: 'z.B. 175',
    appVersion: 'Version 1.0.0 · Gemacht mit ❤️',

    forTheBrave: 'Für die Mutigen',
    startBtn: 'STARTEN',
    dayLabel: 'TAG',
    pctFinished: '% Abgeschlossen',
    aiRecommendation: 'KI-Empfehlung ✨',
    thisWeek: 'diese Woche',
    continueWorkout: 'Training fortsetzen',
    discard: 'Verwerfen',
    resumeBtn: 'Fortsetzen',
    noExercisesFound: 'Keine Übungen gefunden',
    exerciseOfLabel: 'Übung',
    ofLabel: 'von',
    nextLabel: 'Weiter',
    finishLabel: 'Fertigstellen',
    skipRest: 'Pause überspringen →',
    calories: 'Kalorien',
    completedLabel: 'Abgeschlossen',
    timeLabel: 'Zeit',
    abs28Name: 'ABS CHALLENGE',
    abs28Desc: 'Tägliches Core-Training für sichtbare Bauchmuskeln in 4 Wochen',
    abs28Short: '28 TAGE',
    fullbody30Name: 'GANZKÖRPER',
    fullbody30Desc: 'Progressives Ganzkörperprogramm vom Anfänger bis zur Elite',
    fullbody30Short: '30 TAGE',
    fatburn14Name: 'FETTVERBRENNUNG',
    fatburn14Desc: 'Intensives 2-Wochen-Protokoll für schnellen Fettverlust',
    fatburn14Short: '14 TAGE',
    logoutBtn: 'Abmelden',
    logoutSub: 'Von deinem Konto abmelden',
    chatGreeting: 'Hallo! Ich bin dein KI-Fitness-Coach 💪 Frag mich zu Workouts, Ernährung oder Erholung!',
    chatPlaceholder: 'Frag einfach…',
    chatOnline: 'Online',
    chatErrorMsg: 'Verbindung fehlgeschlagen. Bitte erneut versuchen!',
    chatPrompt1: 'Schneller Muskeln aufbauen?',
    chatPrompt2: 'Beste Übungen zum Fettverbrennen?',
    chatPrompt3: 'Wie viele Ruhetage?',
    chatPrompt4: 'Ernährung vor dem Training?',
    chatPrompt5: 'Flexibilität verbessern?',
    chatPrompt6: 'Wöchentlicher Trainingsplan',
  },

  hi: {
    training: 'प्रशिक्षण', discover: 'खोजें', report: 'रिपोर्ट', settings: 'सेटिंग्स',
    trainingSub: 'आपका व्यक्तिगत प्रशिक्षण केंद्र',
    discoverSub: 'वर्कआउट और व्यायाम खोजें',
    reportSub: 'अपनी फिटनेस प्रगति ट्रैक करें',
    settingsSub: 'ऐप प्राथमिकताएं और प्रोफाइल',

    chooseBodyPart: 'मांसपेशी समूह चुनें',
    chooseBodyPartSub: 'आज के लिए मांसपेशी समूह चुनें',
    chooseLevel: 'स्तर चुनें',
    chooseLevelSub: 'अपनी कठिनाई चुनें',
    chooseMode: 'मोड चुनें',
    chooseModeSub: 'आज कहाँ प्रशिक्षण कर रहे हैं?',
    startWorkout: 'वर्कआउट शुरू करें',
    back: 'वापस',
    skip: 'छोड़ें',
    pause: 'रोकें',
    resume: 'जारी रखें',
    rest: 'आराम',
    complete: 'पूर्ण करें',
    getReady: 'तैयार हो जाएं',
    exercise: 'व्यायाम',
    exercises: 'व्यायाम',
    nextExercise: 'अगला व्यायाम',
    workoutComplete: 'वर्कआउट पूर्ण!',
    totalCalories: 'कुल कैलोरी',
    totalReps: 'कुल दोहराव',
    duration: 'अवधि',
    done: 'हो गया',
    reps: 'दोहराव',
    sec: 'सेकंड',
    sets: 'सेट',
    programs: 'प्रोग्राम',
    selectProgram: 'प्रोग्राम चुनें',
    bp_full_body: 'पूरा शरीर', bp_full_body_sub: 'पूर्ण शरीर शक्ति और कार्डियो',
    bp_chest: 'छाती', bp_chest_sub: 'पेक्टोरल, ऊपरी शरीर पुश',
    bp_arms: 'बाहें', bp_arms_sub: 'बाइसेप्स, ट्राइसेप्स और फोरआर्म्स',
    bp_legs: 'पैर', bp_legs_sub: 'क्वाड्स, हैमस्ट्रिंग और ग्लूट्स',
    bp_back: 'पीठ', bp_back_sub: 'लैट्स, ट्रैप्स और पोस्टीरियर चेन',
    bp_abs: 'पेट', bp_abs_sub: 'कोर शक्ति और परिभाषा',
    beginner: 'शुरुआती', beginner_tag: 'अपनी नींव बनाएं',
    intermediate: 'मध्यवर्ती', intermediate_tag: 'अपना स्तर बढ़ाएं',
    advanced: 'उन्नत', advanced_tag: 'अपनी सीमाओं को पार करें',
    mode_home: 'घर', mode_home_sub: 'फ्रीहैंड और बॉडीवेट',
    mode_home_desc: 'कोई उपकरण नहीं चाहिए। बॉडीवेट मूवमेंट से कहीं भी ट्रेन करें।',
    mode_gym: 'जिम', mode_gym_sub: 'वज़न और मशीनें',
    mode_gym_desc: 'पूरा जिम एक्सेस। बारबेल, डम्बल, केबल और मशीनें।',

    searchPlaceholder: 'वर्कआउट खोजें…',
    workoutType: 'वर्कआउट प्रकार', close: 'बंद करें',
    allCategories: 'सभी',
    filterLevel: 'स्तर',
    filterDuration: 'अवधि',
    noResults: 'कोई परिणाम नहीं',
    tryFilters: 'फ़िल्टर समायोजित करने का प्रयास करें',
    cantFind: 'जो चाहते हैं वह नहीं मिला?',
    tellUs: '✏️ हमें बताएं आपको क्या चाहिए',
    results: 'परिणाम',
    result: 'परिणाम',
    min: 'मिनट',
    startSession: 'वर्कआउट शुरू करें',
    exercises_label: 'व्यायाम',
    wt_muscle: 'मांसपेशी बनाएं', wt_warmup: 'वार्म-अप', wt_fat: 'वसा जलाएं',
    wt_equipment: 'उपकरण के साथ', wt_stretching: 'स्ट्रेचिंग', wt_cardio: 'कार्डियो',
    lvl_beginner: 'शुरुआती', lvl_intermediate: 'मध्यवर्ती', lvl_advanced: 'उन्नत',
    history: 'इतिहास',
    weeklySummary: 'साप्ताहिक सारांश',
    workoutsLabel: 'वर्कआउट',
    workoutsLabelP: 'वर्कआउट',
    noWorkoutsYet: 'अभी तक कोई वर्कआउट नहीं',
    noWorkoutsDesc: 'अपना इतिहास यहाँ देखने के लिए एक वर्कआउट पूरा करें।',
    picksForYou: 'आपके लिए', startNow: 'अभी शुरू करें ▶', forBeginners: 'शुरुआती के लिए 🌱',
    challengesLabel: 'चुनौतियां', stretchRecovery: 'स्ट्रेचिंग & रिकवरी', stayActive: 'सक्रिय रहें,\nआकार में रहें',

    reportTitle: 'रिपोर्ट',
    statsWorkouts: 'वर्कआउट',
    statsKcal: 'किलो-कैलोरी',
    statsMinutes: 'मिनट',
    allRecords: 'सभी रिकॉर्ड →',
    closeHistory: 'बंद करें ✕',
    fullHistory: 'पूरा इतिहास',
    weeklyActivity: 'साप्ताहिक गतिविधि',
    weeklyActivitySub: 'इस सप्ताह प्रति दिन जली कैलोरी',
    totalKcal: 'कुल किलो-कैलोरी',
    recentSessions: 'हालिया सत्र',
    noSessionsYet: 'अभी तक कोई सत्र नहीं',
    noSessionsDesc: 'अपना इतिहास देखने के लिए ट्रेनिंग टैब में एक वर्कआउट पूरा करें',
    weightTracking: 'वज़न ट्रैकिंग',
    current: 'वर्तमान',
    vsFirst: 'पहली प्रविष्टि बनाम',
    logWeight: 'वज़न दर्ज करें (kg)',
    log: 'दर्ज करें',
    bmiCalculator: 'बीएमआई कैलकुलेटर',
    bmiSub: 'बॉडी मास इंडेक्स',
    weightKg: 'वज़न (kg)',
    heightCm: 'ऊंचाई (cm)',
    calcBmi: 'बीएमआई गणना करें',
    yourBmi: 'आपका बीएमआई स्कोर',
    consistencyTitle: 'निरंतरता विश्लेषक',
    consistencySub: 'अपना ड्रॉपआउट जोखिम जांचें और प्रेरणा पाएं',
    daysMissed: 'छूटे हुए दिन (इस सप्ताह)',
    consistencyScore: 'निरंतरता स्कोर (0–100)',
    analyzeBtn: 'मेरी निरंतरता विश्लेषण करें',
    dropoutRisk: 'छोड़ने का जोखिम',
    totalSessions: 'कुल सत्र',
    keepGoing: 'जारी रखें!',
    exercisesDone: 'व्यायाम पूर्ण',
    totalCompleted: 'कुल पूर्ण',
    today: 'आज',
    yesterday: 'कल',
    daysAgo: 'दिन पहले',
    quickSession: 'त्वरित सत्र',

    preferences: 'प्राथमिकताएं',
    settingsTitle: 'सेटिंग्स',
    freePlan: 'मुफ्त योजना · प्रोफाइल संपादित करें',
    upgradePremium: 'प्रीमियम में अपग्रेड करें',
    upgradeDesc: 'एआई पोज़ डिटेक्शन, कस्टम प्लान और अधिक अनलॉक करें',
    upgrade: 'अपग्रेड →',
    saveProfile: 'प्रोफाइल सहेजें',
    saved: '✅ सहेजा गया!',
    sectionWorkout: 'वर्कआउट',
    sectionAudio: 'ऑडियो और आवाज़',
    sectionApp: 'ऐप',
    sectionData: 'डेटा',
    restTime: 'आराम का समय',
    restTimeSub: 'सेट के बीच सेकंड',
    units: 'इकाइयां',
    unitsSub: 'मेट्रिक या इंपीरियल',
    unitsMetric: 'मेट्रिक (kg/cm)',
    unitsImperial: 'इंपीरियल (lb/in)',
    difficulty: 'कठिनाई',
    difficultySub: 'प्रदर्शन के आधार पर स्वतः समायोजन',
    soundEffects: 'ध्वनि प्रभाव',
    soundEffectsSub: 'व्यायाम संकेत और बदलाव',
    voiceCoach: 'वॉयस कोच',
    voiceCoachSub: 'वर्कआउट के दौरान ऑडियो मार्गदर्शन',
    voiceCoachSpeaking: 'AI कोच बोल रहा है…',
    notifications: 'सूचनाएं',
    notificationsSub: 'वर्कआउट रिमाइंडर और स्ट्रीक',
    language: 'भाषा',
    languageSub: 'प्रदर्शन भाषा',
    darkMode: 'डार्क मोड',
    darkModeSub: 'डार्क थीम सक्षम करें',
    healthSync: 'स्वास्थ्य सिंक',
    healthSyncSub: 'Apple Health / Google Fit से सिंक करें',
    backup: 'बैकअप और रिस्टोर',
    backupSub: 'क्लाउड पर प्रगति सिंक करें',
    backupBtn: 'बैकअप',
    clearData: 'डेटा साफ़ करें',
    clearDataSub: 'सभी वर्कआउट इतिहास हटाएं',
    clearBtn: 'साफ़ करें',
    healthSyncMsg: 'स्वास्थ्य सिंक के लिए FitAI मोबाइल ऐप आवश्यक है।',
    healthSyncMsgDesc: 'Apple Health या Google Fit से सिंक करने के लिए iPhone या Android पर FitAI ऐप डाउनलोड करें।',
    aiCoachHint: 'चैट के लिए कहीं भी 🤖 बटन दबाएं',
    name: 'नाम', namePlaceholder: 'आपका नाम',
    age: 'आयु', agePlaceholder: 'जैसे 25',
    weightLabel: 'वज़न (kg)', weightPlaceholder: 'जैसे 70',
    heightLabel: 'ऊंचाई (cm)', heightPlaceholder: 'जैसे 175',
    appVersion: 'संस्करण 1.0.0 · ❤️ के साथ बनाया गया',

    forTheBrave: 'साहसियों के लिए',
    startBtn: 'शुरू करें',
    dayLabel: 'दिन',
    pctFinished: '% पूर्ण',
    aiRecommendation: 'AI अनुशंसा ✨',
    thisWeek: 'इस सप्ताह',
    continueWorkout: 'वर्कआउट जारी करें',
    discard: 'रद्द करें',
    resumeBtn: 'फिर से शुरू करें',
    noExercisesFound: 'कोई व्यायाम नहीं मिला',
    exerciseOfLabel: 'व्यायाम',
    ofLabel: 'में से',
    nextLabel: 'अगला',
    finishLabel: 'समाप्त',
    skipRest: 'आराम छोड़ें →',
    calories: 'कैलोरी',
    completedLabel: 'पूर्ण',
    timeLabel: 'समय',
    abs28Name: 'ABS चैलेंज',
    abs28Desc: '4 सप्ताह में दिखाई देने वाले एब्स के लिए दैनिक कोर वर्क',
    abs28Short: '28 दिन',
    fullbody30Name: 'फुल बॉडी',
    fullbody30Desc: 'शुरुआत से एलीट तक प्रगतिशील पूरे शरीर का कार्यक्रम',
    fullbody30Short: '30 दिन',
    fatburn14Name: 'फैट बर्न',
    fatburn14Desc: 'तेजी से वसा घटाने के लिए 2 सप्ताह का गहन प्रोटोकॉल',
    fatburn14Short: '14 दिन',
    logoutBtn: 'लॉग आउट',
    logoutSub: 'अपने खाते से बाहर निकलें',
    chatGreeting: 'नमस्ते! मैं आपका AI फिटनेस कोच हूं 💪 वर्कआउट, पोषण या रिकवरी के बारे में पूछें!',
    chatPlaceholder: 'कुछ भी पूछें…',
    chatOnline: 'ऑनलाइन',
    chatErrorMsg: 'कनेक्ट नहीं हो सका। दोबारा कोशिश करें!',
    chatPrompt1: 'तेज़ी से मांसपेशियां बनाएं?',
    chatPrompt2: 'सबसे अच्छे फैट लॉस व्यायाम?',
    chatPrompt3: 'कितने आराम के दिन?',
    chatPrompt4: 'वर्कआउट से पहले पोषण?',
    chatPrompt5: 'लचीलापन सुधारें?',
    chatPrompt6: 'साप्ताहिक ट्रेनिंग प्लान',
  },

  pt: {
    training: 'Treino', discover: 'Descobrir', report: 'Relatório', settings: 'Configurações',
    trainingSub: 'Seu centro de treino personalizado',
    discoverSub: 'Explore exercícios e treinos',
    reportSub: 'Acompanhe seu progresso fitness',
    settingsSub: 'Preferências e perfil do app',

    chooseBodyPart: 'Escolha o Grupo Muscular',
    chooseBodyPartSub: 'Selecione o músculo a treinar hoje',
    chooseLevel: 'Escolha o Nível',
    chooseLevelSub: 'Selecione sua dificuldade',
    chooseMode: 'Escolha o Modo',
    chooseModeSub: 'Onde você está treinando hoje?',
    startWorkout: 'Iniciar Treino',
    back: 'Voltar',
    skip: 'Pular',
    pause: 'Pausar',
    resume: 'Retomar',
    rest: 'Descanso',
    complete: 'Concluir',
    getReady: 'Prepare-se',
    exercise: 'Exercício',
    exercises: 'exercícios',
    nextExercise: 'Próximo Exercício',
    workoutComplete: 'Treino Concluído!',
    totalCalories: 'Calorias Totais',
    totalReps: 'Repetições Totais',
    duration: 'Duração',
    done: 'Feito',
    reps: 'reps',
    sec: 'seg',
    sets: 'séries',
    programs: 'Programas',
    selectProgram: 'Selecionar Programa',
    bp_full_body: 'Corpo Inteiro', bp_full_body_sub: 'Força total e cardio',
    bp_chest: 'Peito', bp_chest_sub: 'Peitoral, empurrar parte superior',
    bp_arms: 'Braços', bp_arms_sub: 'Bíceps, tríceps e antebraços',
    bp_legs: 'Pernas', bp_legs_sub: 'Quadríceps, isquiotibiais e glúteos',
    bp_back: 'Costas', bp_back_sub: 'Dorsais, trapézios e cadeia posterior',
    bp_abs: 'Abdômen', bp_abs_sub: 'Força e definição do core',
    beginner: 'Iniciante', beginner_tag: 'Construa sua base',
    intermediate: 'Intermediário', intermediate_tag: 'Suba de nível',
    advanced: 'Avançado', advanced_tag: 'Supere seus limites',
    mode_home: 'Casa', mode_home_sub: 'Livre e peso corporal',
    mode_home_desc: 'Sem equipamento. Treine em qualquer lugar com movimentos de peso corporal.',
    mode_gym: 'Academia', mode_gym_sub: 'Pesos e máquinas',
    mode_gym_desc: 'Acesso completo à academia. Barras, halteres, cabos e máquinas.',

    searchPlaceholder: 'Pesquisar treinos…',
    workoutType: 'Tipo de Treino', close: 'Fechar',
    allCategories: 'Todos',
    filterLevel: 'Nível',
    filterDuration: 'Duração',
    noResults: 'Nenhum resultado',
    tryFilters: 'Tente ajustar os filtros',
    cantFind: 'Não encontrou o que procura?',
    tellUs: '✏️ Diga-nos o que você precisa',
    results: 'resultados',
    result: 'resultado',
    min: 'min',
    startSession: 'Iniciar Treino',
    exercises_label: 'Exercícios',
    wt_muscle: 'Ganhar Músculo', wt_warmup: 'Aquecimento', wt_fat: 'Queima de Gordura',
    wt_equipment: 'Com Equipamento', wt_stretching: 'Alongamento', wt_cardio: 'Cardio',
    lvl_beginner: 'Iniciante', lvl_intermediate: 'Intermediário', lvl_advanced: 'Avançado',
    history: 'Histórico',
    weeklySummary: 'Resumo Semanal',
    workoutsLabel: 'Treino',
    workoutsLabelP: 'Treinos',
    noWorkoutsYet: 'Ainda sem treinos',
    noWorkoutsDesc: 'Conclua um treino para ver seu histórico aqui.',
    picksForYou: 'Para você', startNow: 'Começar ▶', forBeginners: 'Para Iniciantes 🌱',
    challengesLabel: 'Desafios', stretchRecovery: 'Alongamento & Recuperação', stayActive: 'Fique ativo,\nfique em forma',

    reportTitle: 'RELATÓRIO',
    statsWorkouts: 'Treinos',
    statsKcal: 'Kcal',
    statsMinutes: 'Minutos',
    allRecords: 'Todos os registros →',
    closeHistory: 'Fechar ✕',
    fullHistory: 'Histórico Completo',
    weeklyActivity: 'Atividade Semanal',
    weeklyActivitySub: 'Calorias queimadas por dia esta semana',
    totalKcal: 'Kcal total',
    recentSessions: 'Sessões Recentes',
    noSessionsYet: 'Ainda sem sessões',
    noSessionsDesc: 'Conclua um treino na aba Treino para ver seu histórico aqui',
    weightTracking: 'Controle de Peso',
    current: 'Atual',
    vsFirst: 'vs primeiro registro',
    logWeight: 'Registrar peso (kg)',
    log: 'Registrar',
    bmiCalculator: 'Calculadora de IMC',
    bmiSub: 'Índice de Massa Corporal',
    weightKg: 'PESO (kg)',
    heightCm: 'ALTURA (cm)',
    calcBmi: 'Calcular IMC',
    yourBmi: 'Sua Pontuação de IMC',
    consistencyTitle: 'Analisador de Consistência',
    consistencySub: 'Verifique seu risco de desistência e obtenha motivação',
    daysMissed: 'DIAS PERDIDOS (esta semana)',
    consistencyScore: 'PONTUAÇÃO DE CONSISTÊNCIA (0–100)',
    analyzeBtn: 'Analisar Minha Consistência',
    dropoutRisk: 'RISCO DE DESISTÊNCIA',
    totalSessions: 'Sessões Totais',
    keepGoing: 'Continue!',
    exercisesDone: 'Exercícios Feitos',
    totalCompleted: 'Total concluído',
    today: 'Hoje',
    yesterday: 'Ontem',
    daysAgo: 'dias atrás',
    quickSession: 'Sessão rápida',

    preferences: 'Preferências',
    settingsTitle: 'Configurações',
    freePlan: 'Plano Gratuito · Editar Perfil',
    upgradePremium: 'Assinar Premium',
    upgradeDesc: 'Desbloqueie detecção de pose IA, planos personalizados e mais',
    upgrade: 'Melhorar →',
    saveProfile: 'Salvar Perfil',
    saved: '✅ Salvo!',
    sectionWorkout: 'TREINO',
    sectionAudio: 'ÁUDIO E VOZ',
    sectionApp: 'APLICATIVO',
    sectionData: 'DADOS',
    restTime: 'Tempo de Descanso',
    restTimeSub: 'Segundos entre séries',
    units: 'Unidades',
    unitsSub: 'Métrico ou Imperial',
    unitsMetric: 'Métrico (kg/cm)',
    unitsImperial: 'Imperial (lb/in)',
    difficulty: 'Dificuldade',
    difficultySub: 'Ajuste automático com base no desempenho',
    soundEffects: 'Efeitos Sonoros',
    soundEffectsSub: 'Sinais de exercício e transições',
    voiceCoach: 'Treinador de Voz',
    voiceCoachSub: 'Orientação de áudio durante treinos',
    voiceCoachSpeaking: 'Treinador IA falando…',
    notifications: 'Notificações',
    notificationsSub: 'Lembretes e sequências de treino',
    language: 'Idioma',
    languageSub: 'Idioma de exibição',
    darkMode: 'Modo Escuro',
    darkModeSub: 'Ativar tema escuro',
    healthSync: 'Sincronização de Saúde',
    healthSyncSub: 'Sincronizar com Apple Health / Google Fit',
    backup: 'Backup e Restauração',
    backupSub: 'Sincronize seu progresso na nuvem',
    backupBtn: 'Backup',
    clearData: 'Limpar Dados',
    clearDataSub: 'Excluir todo o histórico de treinos',
    clearBtn: 'Limpar',
    healthSyncMsg: 'A sincronização de saúde requer o aplicativo móvel FitAI.',
    healthSyncMsgDesc: 'Baixe o app FitAI no iPhone ou Android para sincronizar com Apple Health ou Google Fit.',
    aiCoachHint: 'Toque no botão 🤖 em qualquer lugar para conversar',
    name: 'Nome', namePlaceholder: 'Seu nome',
    age: 'Idade', agePlaceholder: 'ex. 25',
    weightLabel: 'Peso (kg)', weightPlaceholder: 'ex. 70',
    heightLabel: 'Altura (cm)', heightPlaceholder: 'ex. 175',
    appVersion: 'Versão 1.0.0 · Feito com ❤️',

    forTheBrave: 'Para os corajosos',
    startBtn: 'INICIAR',
    dayLabel: 'DIA',
    pctFinished: '% Concluído',
    aiRecommendation: 'Recomendação IA ✨',
    thisWeek: 'esta semana',
    continueWorkout: 'Continuar Treino',
    discard: 'Descartar',
    resumeBtn: 'Retomar',
    noExercisesFound: 'Nenhum exercício encontrado',
    exerciseOfLabel: 'Exercício',
    ofLabel: 'de',
    nextLabel: 'Próximo',
    finishLabel: 'Finalizar',
    skipRest: 'Pular descanso →',
    calories: 'Calorias',
    completedLabel: 'Concluído',
    timeLabel: 'Tempo',
    abs28Name: 'DESAFIO ABS',
    abs28Desc: 'Trabalho diário de core para abdômen visível em 4 semanas',
    abs28Short: '28 DIAS',
    fullbody30Name: 'CORPO INTEIRO',
    fullbody30Desc: 'Programa progressivo de corpo inteiro do iniciante ao elite',
    fullbody30Short: '30 DIAS',
    fatburn14Name: 'QUEIMA DE GORDURA',
    fatburn14Desc: 'Protocolo intenso de 2 semanas para perda rápida de gordura',
    fatburn14Short: '14 DIAS',
    logoutBtn: 'Sair',
    logoutSub: 'Sair da sua conta',
    chatGreeting: 'Olá! Sou o seu Treinador IA 💪 Pergunte-me sobre treinos, nutrição ou recuperação!',
    chatPlaceholder: 'Pergunte qualquer coisa…',
    chatOnline: 'Online',
    chatErrorMsg: 'Não foi possível conectar. Tente novamente!',
    chatPrompt1: 'Ganhar músculo mais rápido?',
    chatPrompt2: 'Melhores exercícios para perda de gordura?',
    chatPrompt3: 'Quantos dias de descanso?',
    chatPrompt4: 'Nutrição pré-treino?',
    chatPrompt5: 'Melhorar a flexibilidade?',
    chatPrompt6: 'Plano de treino semanal',
  },
};

const AppSettingsContext = createContext(null);

export function AppSettingsProvider({ children }) {
  const [darkMode, setDarkModeState] = useState(false);
  const [language, setLanguageState] = useState('en');
  const [notifications, setNotificationsState] = useState(false);
  const [healthSync, setHealthSyncState] = useState(false);
  const [voiceCoach, setVoiceCoachState] = useState(false);
  const [hydrated, setHydrated] = useState(false);
  const [navTarget, setNavTarget] = useState(null);

  const navigateTo = useCallback((tab, subView = null) => {
    setNavTarget({ tab, subView });
  }, []);

  const clearNavTarget = useCallback(() => setNavTarget(null), []);

  useEffect(() => {
    try {
      const dm = localStorage.getItem('fitai_darkMode');
      const lang = localStorage.getItem('fitai_language');
      const notif = localStorage.getItem('fitai_notifications');
      const hs = localStorage.getItem('fitai_healthSync');
      const vc = localStorage.getItem('fitai_voiceCoach');
      if (dm !== null) setDarkModeState(dm === 'true');
      if (lang) setLanguageState(lang);
      if (notif !== null) setNotificationsState(notif === 'true');
      if (hs !== null) setHealthSyncState(hs === 'true');
      if (vc !== null) setVoiceCoachState(vc === 'true');
    } catch {}
    setHydrated(true);
  }, []);

  useEffect(() => {
    if (!hydrated) return;
    if (darkMode) {
      document.documentElement.setAttribute('data-theme', 'dark');
    } else {
      document.documentElement.removeAttribute('data-theme');
    }
    try { localStorage.setItem('fitai_darkMode', String(darkMode)); } catch {}
  }, [darkMode, hydrated]);

  useEffect(() => {
    if (!hydrated) return;
    try { localStorage.setItem('fitai_language', language); } catch {}
  }, [language, hydrated]);

  useEffect(() => {
    if (!hydrated) return;
    try { localStorage.setItem('fitai_notifications', String(notifications)); } catch {}
  }, [notifications, hydrated]);

  useEffect(() => {
    if (!hydrated) return;
    try { localStorage.setItem('fitai_healthSync', String(healthSync)); } catch {}
  }, [healthSync, hydrated]);

  useEffect(() => {
    if (!hydrated) return;
    try { localStorage.setItem('fitai_voiceCoach', String(voiceCoach)); } catch {}
  }, [voiceCoach, hydrated]);

  const setDarkMode = useCallback((val) => setDarkModeState(val), []);
  const setLanguage = useCallback((val) => setLanguageState(val), []);
  const setHealthSync = useCallback((val) => setHealthSyncState(val), []);
  const setVoiceCoach = useCallback((val) => setVoiceCoachState(val), []);

  const setNotifications = useCallback(async (val) => {
    if (val && typeof window !== 'undefined' && 'Notification' in window) {
      const perm = await Notification.requestPermission();
      if (perm === 'granted') {
        new Notification('FitAI', { body: 'Notifications enabled! Time to work out! 💪', icon: '/favicon.ico' });
        setNotificationsState(true);
      } else {
        setNotificationsState(false);
      }
    } else {
      setNotificationsState(val);
    }
  }, []);

  const t = TRANSLATIONS[language] || TRANSLATIONS.en;

  return (
    <AppSettingsContext.Provider value={{
      darkMode, setDarkMode,
      language, setLanguage,
      notifications, setNotifications,
      healthSync, setHealthSync,
      voiceCoach, setVoiceCoach,
      t,
      navTarget, navigateTo, clearNavTarget,
    }}>
      {children}
    </AppSettingsContext.Provider>
  );
}

export function useAppSettings() {
  const ctx = useContext(AppSettingsContext);
  if (!ctx) throw new Error('useAppSettings must be used within AppSettingsProvider');
  return ctx;
}

export { TRANSLATIONS };
