export type ExerciseCategory =
  | "freehand"
  | "gym"
  | "calisthenics"
  | "martial_arts"
  | "yoga"
  | "cardio"
  | "rehab";

export type DifficultyLevel = "beginner" | "intermediate" | "advanced";

export type Equipment =
  | "none"
  | "dumbbell"
  | "barbell"
  | "machine"
  | "band"
  | "kettlebell"
  | "cable"
  | "mat"
  | "pullup_bar"
  | "parallel_bars"
  | "rings"
  | "bag"
  | "rope";

export type MovementPattern =
  | "push"
  | "pull"
  | "squat"
  | "hinge"
  | "rotation"
  | "strike"
  | "hold"
  | "carry"
  | "cardio"
  | "mobility"
  | "balance";

export interface Exercise {
  id: string;
  name: string;
  category: ExerciseCategory;
  subcategory: string;
  equipment: Equipment[];
  movement_pattern: MovementPattern;
  muscle_groups: string[];
  targetMuscles: string[];
  difficulty: DifficultyLevel;
  is_compound: boolean;
  variations: string[];
  description: string;
  instructions: string[];
  caloriesPerRep: number;
  repDuration: number;
  met_value: number;
  icon: string;
  color: string;
}

export interface ExerciseGroup {
  subcategory: string;
  exercises: Exercise[];
}

export const EXERCISES: Exercise[] = [
  // ─────────────────── GYM ───────────────────
  {
    id: "bench_press",
    name: "Bench Press",
    category: "gym",
    subcategory: "Chest",
    equipment: ["barbell"],
    movement_pattern: "push",
    muscle_groups: ["Chest", "Triceps", "Anterior Deltoid"],
    targetMuscles: ["Chest", "Triceps", "Anterior Deltoid"],
    difficulty: "intermediate",
    is_compound: true,
    variations: ["Incline Bench Press", "Decline Bench Press", "Close-Grip Bench Press"],
    description: "The primary compound lift for chest development. Builds mass and strength.",
    instructions: [
      "Lie on bench with eyes under the bar",
      "Grip bar slightly wider than shoulder-width",
      "Unrack and lower bar to mid-chest",
      "Touch chest lightly without bouncing",
      "Press bar back up powerfully",
    ],
    caloriesPerRep: 0.7,
    repDuration: 4,
    met_value: 5.0,
    icon: "barbell-outline",
    color: "#FF6B35",
  },
  {
    id: "incline_bench_press",
    name: "Incline Bench Press",
    category: "gym",
    subcategory: "Chest",
    equipment: ["barbell"],
    movement_pattern: "push",
    muscle_groups: ["Upper Chest", "Triceps", "Anterior Deltoid"],
    targetMuscles: ["Upper Chest", "Anterior Deltoid"],
    difficulty: "intermediate",
    is_compound: true,
    variations: ["Incline Dumbbell Press", "Incline Cable Fly"],
    description: "Angled press that targets the upper pectoral muscle for complete chest development.",
    instructions: [
      "Set bench to 30-45 degree incline",
      "Grip barbell shoulder-width apart",
      "Lower bar to upper chest",
      "Drive bar up and slightly back",
      "Lock out at top and repeat",
    ],
    caloriesPerRep: 0.65,
    repDuration: 4,
    met_value: 4.8,
    icon: "barbell-outline",
    color: "#FF6B35",
  },
  {
    id: "chest_fly",
    name: "Cable Chest Fly",
    category: "gym",
    subcategory: "Chest",
    equipment: ["cable"],
    movement_pattern: "push",
    muscle_groups: ["Chest", "Anterior Deltoid"],
    targetMuscles: ["Chest", "Anterior Deltoid"],
    difficulty: "beginner",
    is_compound: false,
    variations: ["Dumbbell Fly", "Pec Deck", "Low Cable Fly"],
    description: "Isolation exercise for chest using the cable machine for constant tension.",
    instructions: [
      "Stand between cable stacks at chest height",
      "Hold handles with slight elbow bend",
      "Bring hands together in front of chest",
      "Squeeze chest at peak contraction",
      "Return slowly with control",
    ],
    caloriesPerRep: 0.5,
    repDuration: 4,
    met_value: 3.5,
    icon: "barbell-outline",
    color: "#FF6B35",
  },
  {
    id: "lat_pulldown",
    name: "Lat Pulldown",
    category: "gym",
    subcategory: "Back",
    equipment: ["cable"],
    movement_pattern: "pull",
    muscle_groups: ["Lats", "Biceps", "Rhomboids", "Rear Deltoid"],
    targetMuscles: ["Lats", "Biceps", "Rhomboids"],
    difficulty: "beginner",
    is_compound: true,
    variations: ["Wide Grip", "Narrow Grip", "Reverse Grip", "Single Arm"],
    description: "Cable machine exercise that builds wide back muscles and V-taper.",
    instructions: [
      "Grip bar wider than shoulder-width",
      "Sit with thighs locked under pad",
      "Lean back 15-20 degrees",
      "Pull bar to upper chest",
      "Squeeze lats at bottom and return slowly",
    ],
    caloriesPerRep: 0.6,
    repDuration: 4,
    met_value: 4.0,
    icon: "barbell-outline",
    color: "#3B82F6",
  },
  {
    id: "seated_cable_row",
    name: "Seated Cable Row",
    category: "gym",
    subcategory: "Back",
    equipment: ["cable"],
    movement_pattern: "pull",
    muscle_groups: ["Middle Back", "Lats", "Biceps", "Rear Deltoid"],
    targetMuscles: ["Middle Back", "Lats", "Biceps"],
    difficulty: "beginner",
    is_compound: true,
    variations: ["Wide Grip Row", "Single Arm Row", "High Row"],
    description: "Cable row that targets the mid-back and builds thickness.",
    instructions: [
      "Sit at cable machine with feet on platform",
      "Grab handle with both hands",
      "Keep back straight and row to midsection",
      "Squeeze shoulder blades together",
      "Return with full control",
    ],
    caloriesPerRep: 0.55,
    repDuration: 4,
    met_value: 4.0,
    icon: "barbell-outline",
    color: "#3B82F6",
  },
  {
    id: "deadlift",
    name: "Barbell Deadlift",
    category: "gym",
    subcategory: "Back",
    equipment: ["barbell"],
    movement_pattern: "hinge",
    muscle_groups: ["Hamstrings", "Glutes", "Lower Back", "Traps", "Core"],
    targetMuscles: ["Hamstrings", "Glutes", "Lower Back"],
    difficulty: "advanced",
    is_compound: true,
    variations: ["Romanian Deadlift", "Sumo Deadlift", "Trap Bar Deadlift"],
    description: "The king of all lifts. Builds total-body strength and muscle mass.",
    instructions: [
      "Stand with bar over mid-foot",
      "Hinge at hips, grip bar shoulder-width",
      "Push chest out, flatten back",
      "Drive through floor as bar passes knees",
      "Lock hips forward at top",
    ],
    caloriesPerRep: 1.1,
    repDuration: 5,
    met_value: 6.0,
    icon: "barbell-outline",
    color: "#3B82F6",
  },
  {
    id: "leg_press",
    name: "Leg Press",
    category: "gym",
    subcategory: "Legs",
    equipment: ["machine"],
    movement_pattern: "squat",
    muscle_groups: ["Quads", "Glutes", "Hamstrings"],
    targetMuscles: ["Quads", "Glutes", "Hamstrings"],
    difficulty: "beginner",
    is_compound: true,
    variations: ["Wide Stance", "Narrow Stance", "Single Leg"],
    description: "Machine-based compound leg exercise that allows safe heavy loading.",
    instructions: [
      "Sit in machine with back flat against pad",
      "Place feet shoulder-width on platform",
      "Release safety locks carefully",
      "Lower until 90 degree knee angle",
      "Press back up without locking knees",
    ],
    caloriesPerRep: 0.65,
    repDuration: 4,
    met_value: 4.5,
    icon: "barbell-outline",
    color: "#00FF88",
  },
  {
    id: "leg_extension",
    name: "Leg Extension",
    category: "gym",
    subcategory: "Legs",
    equipment: ["machine"],
    movement_pattern: "squat",
    muscle_groups: ["Quads"],
    targetMuscles: ["Quads"],
    difficulty: "beginner",
    is_compound: false,
    variations: ["Single Leg Extension"],
    description: "Isolation exercise for quadriceps using the leg extension machine.",
    instructions: [
      "Sit in machine with pad just above ankles",
      "Align knee joint with pivot point",
      "Extend legs until straight",
      "Pause and squeeze quads",
      "Lower slowly and repeat",
    ],
    caloriesPerRep: 0.4,
    repDuration: 3,
    met_value: 3.0,
    icon: "barbell-outline",
    color: "#00FF88",
  },
  {
    id: "leg_curl",
    name: "Lying Leg Curl",
    category: "gym",
    subcategory: "Legs",
    equipment: ["machine"],
    movement_pattern: "hinge",
    muscle_groups: ["Hamstrings", "Calves"],
    targetMuscles: ["Hamstrings"],
    difficulty: "beginner",
    is_compound: false,
    variations: ["Seated Leg Curl", "Standing Leg Curl"],
    description: "Isolation exercise for hamstrings using the leg curl machine.",
    instructions: [
      "Lie face down on machine",
      "Position pad behind ankle",
      "Curl legs up toward glutes",
      "Squeeze hamstrings at top",
      "Lower slowly to start",
    ],
    caloriesPerRep: 0.4,
    repDuration: 3,
    met_value: 3.0,
    icon: "barbell-outline",
    color: "#00FF88",
  },
  {
    id: "shoulder_press_machine",
    name: "Shoulder Press Machine",
    category: "gym",
    subcategory: "Shoulders",
    equipment: ["machine"],
    movement_pattern: "push",
    muscle_groups: ["Anterior Deltoid", "Lateral Deltoid", "Triceps"],
    targetMuscles: ["Anterior Deltoid", "Lateral Deltoid", "Triceps"],
    difficulty: "beginner",
    is_compound: true,
    variations: ["Dumbbell Press", "Barbell Overhead Press", "Arnold Press"],
    description: "Machine shoulder press for safe, stable overhead pressing.",
    instructions: [
      "Adjust seat so handles align with shoulders",
      "Grip handles with palms forward",
      "Press up until arms nearly extended",
      "Do not fully lock elbows",
      "Lower controlled to start",
    ],
    caloriesPerRep: 0.6,
    repDuration: 3,
    met_value: 4.0,
    icon: "barbell-outline",
    color: "#F59E0B",
  },
  {
    id: "lateral_raise",
    name: "Lateral Raise",
    category: "gym",
    subcategory: "Shoulders",
    equipment: ["dumbbell"],
    movement_pattern: "push",
    muscle_groups: ["Lateral Deltoid", "Supraspinatus"],
    targetMuscles: ["Lateral Deltoid"],
    difficulty: "beginner",
    is_compound: false,
    variations: ["Cable Lateral Raise", "Seated Lateral Raise", "Leaning Lateral Raise"],
    description: "Isolation exercise that builds the side head of the deltoid for width.",
    instructions: [
      "Stand holding dumbbells at sides",
      "Keep slight elbow bend",
      "Raise arms out to sides to shoulder height",
      "Lead with elbow, not wrist",
      "Lower slowly and repeat",
    ],
    caloriesPerRep: 0.35,
    repDuration: 3,
    met_value: 3.0,
    icon: "barbell-outline",
    color: "#F59E0B",
  },
  {
    id: "bicep_curl",
    name: "Dumbbell Bicep Curl",
    category: "gym",
    subcategory: "Arms",
    equipment: ["dumbbell"],
    movement_pattern: "pull",
    muscle_groups: ["Biceps", "Brachialis"],
    targetMuscles: ["Biceps", "Brachialis"],
    difficulty: "beginner",
    is_compound: false,
    variations: ["Hammer Curl", "Preacher Curl", "Concentration Curl", "Cable Curl"],
    description: "Classic dumbbell curl for maximum bicep development.",
    instructions: [
      "Stand or sit holding dumbbells at sides",
      "Supinate wrists as you curl up",
      "Squeeze biceps at top",
      "Do not swing body",
      "Lower slowly to full extension",
    ],
    caloriesPerRep: 0.4,
    repDuration: 3,
    met_value: 3.0,
    icon: "barbell-outline",
    color: "#F59E0B",
  },
  {
    id: "tricep_pushdown",
    name: "Cable Tricep Pushdown",
    category: "gym",
    subcategory: "Arms",
    equipment: ["cable"],
    movement_pattern: "push",
    muscle_groups: ["Triceps"],
    targetMuscles: ["Triceps"],
    difficulty: "beginner",
    is_compound: false,
    variations: ["Rope Pushdown", "Reverse Grip", "Single Arm"],
    description: "Cable isolation exercise for all three heads of the tricep.",
    instructions: [
      "Stand at cable station with bar at chest height",
      "Grip bar overhand, elbows at sides",
      "Push bar down until arms fully extended",
      "Squeeze triceps at bottom",
      "Return slowly to start",
    ],
    caloriesPerRep: 0.35,
    repDuration: 3,
    met_value: 3.0,
    icon: "barbell-outline",
    color: "#F59E0B",
  },
  {
    id: "calf_raise_machine",
    name: "Machine Calf Raise",
    category: "gym",
    subcategory: "Legs",
    equipment: ["machine"],
    movement_pattern: "push",
    muscle_groups: ["Calves", "Soleus"],
    targetMuscles: ["Calves"],
    difficulty: "beginner",
    is_compound: false,
    variations: ["Standing Calf Raise", "Seated Calf Raise", "Donkey Calf Raise"],
    description: "Machine-based isolation for building powerful calf muscles.",
    instructions: [
      "Position shoulders under pads",
      "Place balls of feet on edge of platform",
      "Lower heels as far as comfortable",
      "Rise up on tiptoes explosively",
      "Pause at top and lower slowly",
    ],
    caloriesPerRep: 0.3,
    repDuration: 2,
    met_value: 2.5,
    icon: "barbell-outline",
    color: "#00FF88",
  },

  // ─────────────────── FREEHAND / BODYWEIGHT ───────────────────
  {
    id: "pushup_normal",
    name: "Push-up",
    category: "freehand",
    subcategory: "Chest",
    equipment: ["none"],
    movement_pattern: "push",
    muscle_groups: ["Chest", "Triceps", "Anterior Deltoid", "Core"],
    targetMuscles: ["Chest", "Triceps", "Shoulders"],
    difficulty: "beginner",
    is_compound: true,
    variations: ["Wide Push-up", "Diamond Push-up", "Decline Push-up", "Archer Push-up"],
    description: "The fundamental upper-body push exercise that builds chest, shoulder, and tricep strength.",
    instructions: [
      "Start in plank with hands shoulder-width apart",
      "Keep body in a straight line from head to heels",
      "Lower chest to ground bending elbows at 45°",
      "Push back up to the starting position",
      "Keep core engaged throughout",
    ],
    caloriesPerRep: 0.5,
    repDuration: 3,
    met_value: 3.8,
    icon: "fitness-outline",
    color: "#FF6B35",
  },
  {
    id: "pushup_wide",
    name: "Wide Push-up",
    category: "freehand",
    subcategory: "Chest",
    equipment: ["none"],
    movement_pattern: "push",
    muscle_groups: ["Outer Chest", "Anterior Deltoid"],
    targetMuscles: ["Outer Chest", "Shoulders"],
    difficulty: "beginner",
    is_compound: true,
    variations: ["Normal Push-up", "Stagger Push-up"],
    description: "Wider hand placement targets the outer chest more effectively.",
    instructions: [
      "Place hands 1.5x shoulder-width apart",
      "Keep elbows pointing slightly outward",
      "Lower chest toward ground",
      "Push back up powerfully",
      "Maintain a flat back",
    ],
    caloriesPerRep: 0.55,
    repDuration: 3,
    met_value: 3.9,
    icon: "fitness-outline",
    color: "#FF6B35",
  },
  {
    id: "pushup_diamond",
    name: "Diamond Push-up",
    category: "freehand",
    subcategory: "Chest",
    equipment: ["none"],
    movement_pattern: "push",
    muscle_groups: ["Inner Chest", "Triceps"],
    targetMuscles: ["Inner Chest", "Triceps"],
    difficulty: "intermediate",
    is_compound: true,
    variations: ["Close-Grip Push-up"],
    description: "Close grip push-up with hands forming a diamond shape, targeting triceps.",
    instructions: [
      "Form a diamond shape with thumbs and index fingers",
      "Position hands under your chest",
      "Lower chest to hands",
      "Keep elbows close to body",
      "Press back up strongly",
    ],
    caloriesPerRep: 0.6,
    repDuration: 3,
    met_value: 4.0,
    icon: "fitness-outline",
    color: "#FF6B35",
  },
  {
    id: "squat_bodyweight",
    name: "Bodyweight Squat",
    category: "freehand",
    subcategory: "Legs",
    equipment: ["none"],
    movement_pattern: "squat",
    muscle_groups: ["Quads", "Glutes", "Hamstrings", "Core"],
    targetMuscles: ["Quads", "Glutes", "Hamstrings"],
    difficulty: "beginner",
    is_compound: true,
    variations: ["Jump Squat", "Sumo Squat", "Pistol Squat", "Bulgarian Split Squat"],
    description: "The king of lower body exercises. Builds functional leg strength and mobility.",
    instructions: [
      "Stand with feet shoulder-width apart",
      "Extend arms forward for balance",
      "Lower body bending knees and hips together",
      "Go until thighs are parallel to floor",
      "Drive through heels to stand",
    ],
    caloriesPerRep: 0.4,
    repDuration: 3,
    met_value: 5.0,
    icon: "body-outline",
    color: "#00FF88",
  },
  {
    id: "lunge",
    name: "Forward Lunge",
    category: "freehand",
    subcategory: "Legs",
    equipment: ["none"],
    movement_pattern: "squat",
    muscle_groups: ["Quads", "Glutes", "Hip Flexors"],
    targetMuscles: ["Quads", "Glutes", "Hip Flexors"],
    difficulty: "beginner",
    is_compound: true,
    variations: ["Reverse Lunge", "Walking Lunge", "Lateral Lunge", "Jump Lunge"],
    description: "Unilateral leg exercise that improves balance and targets each leg independently.",
    instructions: [
      "Stand with feet hip-width apart",
      "Step forward with one foot",
      "Lower back knee toward the floor",
      "Keep front knee over ankle",
      "Push back to starting position",
    ],
    caloriesPerRep: 0.45,
    repDuration: 3,
    met_value: 4.5,
    icon: "body-outline",
    color: "#00FF88",
  },
  {
    id: "jump_squat",
    name: "Jump Squat",
    category: "freehand",
    subcategory: "Legs",
    equipment: ["none"],
    movement_pattern: "squat",
    muscle_groups: ["Quads", "Glutes", "Calves"],
    targetMuscles: ["Quads", "Glutes", "Calves"],
    difficulty: "intermediate",
    is_compound: true,
    variations: ["Box Jump", "Tuck Jump"],
    description: "Explosive plyometric squat that builds power and burns significant calories.",
    instructions: [
      "Start in squat position",
      "Explode upward as high as possible",
      "Land softly with knees bent",
      "Immediately drop into next squat",
      "Maintain controlled breathing",
    ],
    caloriesPerRep: 0.8,
    repDuration: 2,
    met_value: 8.0,
    icon: "body-outline",
    color: "#00FF88",
  },
  {
    id: "crunch",
    name: "Crunch",
    category: "freehand",
    subcategory: "Core",
    equipment: ["mat"],
    movement_pattern: "pull",
    muscle_groups: ["Upper Abs", "Rectus Abdominis"],
    targetMuscles: ["Upper Abs"],
    difficulty: "beginner",
    is_compound: false,
    variations: ["Bicycle Crunch", "Reverse Crunch", "Oblique Crunch"],
    description: "Classic abdominal exercise targeting the rectus abdominis.",
    instructions: [
      "Lie on back with knees bent, feet flat",
      "Place hands behind head (don't pull)",
      "Curl upper body toward knees",
      "Focus on squeezing abs",
      "Lower slowly to ground",
    ],
    caloriesPerRep: 0.3,
    repDuration: 2,
    met_value: 3.5,
    icon: "body-outline",
    color: "#A855F7",
  },
  {
    id: "leg_raise",
    name: "Leg Raise",
    category: "freehand",
    subcategory: "Core",
    equipment: ["mat"],
    movement_pattern: "pull",
    muscle_groups: ["Lower Abs", "Hip Flexors"],
    targetMuscles: ["Lower Abs", "Hip Flexors"],
    difficulty: "intermediate",
    is_compound: false,
    variations: ["Hanging Leg Raise", "Flutter Kicks", "Scissor Kicks"],
    description: "Targets the lower abdominal region which is often undertrained.",
    instructions: [
      "Lie flat on back, legs straight",
      "Place hands under hips for support",
      "Raise legs to 90 degrees",
      "Lower slowly without touching floor",
      "Keep lower back pressed down",
    ],
    caloriesPerRep: 0.35,
    repDuration: 3,
    met_value: 4.0,
    icon: "body-outline",
    color: "#A855F7",
  },
  {
    id: "plank",
    name: "Plank Hold",
    category: "freehand",
    subcategory: "Core",
    equipment: ["mat"],
    movement_pattern: "hold",
    muscle_groups: ["Core", "Abs", "Glutes", "Shoulders"],
    targetMuscles: ["Core", "Abs", "Shoulders"],
    difficulty: "beginner",
    is_compound: true,
    variations: ["Side Plank", "Plank with Shoulder Tap", "RKC Plank"],
    description: "Isometric core exercise that builds full-body stability and endurance.",
    instructions: [
      "Start in forearm plank position",
      "Keep body in a straight line",
      "Squeeze glutes and brace core",
      "Do not let hips drop or rise",
      "Breathe steadily throughout",
    ],
    caloriesPerRep: 0.15,
    repDuration: 1,
    met_value: 3.5,
    icon: "body-outline",
    color: "#A855F7",
  },

  // ─────────────────── CALISTHENICS ───────────────────
  {
    id: "pullup",
    name: "Pull-up",
    category: "calisthenics",
    subcategory: "Upper Body Pull",
    equipment: ["pullup_bar"],
    movement_pattern: "pull",
    muscle_groups: ["Lats", "Biceps", "Core", "Rear Deltoid"],
    targetMuscles: ["Lats", "Biceps", "Core"],
    difficulty: "intermediate",
    is_compound: true,
    variations: ["Chin-up", "Wide Grip Pull-up", "Archer Pull-up", "Weighted Pull-up"],
    description: "The gold standard of upper body pulling strength.",
    instructions: [
      "Hang from bar with overhand grip",
      "Hands slightly wider than shoulders",
      "Pull body up until chin clears bar",
      "Squeeze lats at top",
      "Lower with full control",
    ],
    caloriesPerRep: 0.8,
    repDuration: 4,
    met_value: 8.0,
    icon: "body-outline",
    color: "#A855F7",
  },
  {
    id: "dips",
    name: "Parallel Bar Dips",
    category: "calisthenics",
    subcategory: "Upper Body Push",
    equipment: ["parallel_bars"],
    movement_pattern: "push",
    muscle_groups: ["Chest", "Triceps", "Anterior Deltoid"],
    targetMuscles: ["Chest", "Triceps", "Shoulders"],
    difficulty: "intermediate",
    is_compound: true,
    variations: ["Bench Dip", "Ring Dip", "Weighted Dip"],
    description: "Bodyweight dipping movement that builds impressive pushing strength.",
    instructions: [
      "Mount parallel bars with straight arms",
      "Lean forward slightly for chest emphasis",
      "Lower body by bending elbows",
      "Go until upper arms are parallel",
      "Press back up strongly",
    ],
    caloriesPerRep: 0.75,
    repDuration: 4,
    met_value: 7.0,
    icon: "body-outline",
    color: "#A855F7",
  },
  {
    id: "muscle_up",
    name: "Muscle-Up",
    category: "calisthenics",
    subcategory: "Skills",
    equipment: ["pullup_bar"],
    movement_pattern: "pull",
    muscle_groups: ["Lats", "Chest", "Triceps", "Core"],
    targetMuscles: ["Lats", "Chest", "Triceps"],
    difficulty: "advanced",
    is_compound: true,
    variations: ["Ring Muscle-Up", "Weighted Muscle-Up"],
    description: "Combined pull-up and dip above the bar. The pinnacle of upper body calisthenics.",
    instructions: [
      "Generate momentum with a swing",
      "Pull explosively above the bar",
      "Transition elbows over the bar",
      "Push up into a dip position",
      "Lower back down with control",
    ],
    caloriesPerRep: 1.5,
    repDuration: 5,
    met_value: 10.0,
    icon: "body-outline",
    color: "#A855F7",
  },
  {
    id: "l_sit",
    name: "L-Sit Hold",
    category: "calisthenics",
    subcategory: "Skills",
    equipment: ["parallel_bars"],
    movement_pattern: "hold",
    muscle_groups: ["Abs", "Hip Flexors", "Triceps", "Lats"],
    targetMuscles: ["Abs", "Hip Flexors", "Triceps"],
    difficulty: "intermediate",
    is_compound: true,
    variations: ["Tuck L-Sit", "One-Leg L-Sit", "V-Sit"],
    description: "Static hold demonstrating exceptional core and upper body strength.",
    instructions: [
      "Support body on parallel bars with straight arms",
      "Lift legs to horizontal position",
      "Keep feet flexed and pointed forward",
      "Depress shoulders away from ears",
      "Hold position as long as form allows",
    ],
    caloriesPerRep: 1.2,
    repDuration: 10,
    met_value: 6.0,
    icon: "body-outline",
    color: "#A855F7",
  },
  {
    id: "front_lever",
    name: "Front Lever",
    category: "calisthenics",
    subcategory: "Skills",
    equipment: ["pullup_bar"],
    movement_pattern: "hold",
    muscle_groups: ["Lats", "Core", "Rear Deltoid", "Biceps"],
    targetMuscles: ["Lats", "Core", "Shoulders"],
    difficulty: "advanced",
    is_compound: true,
    variations: ["Tuck Front Lever", "Advanced Tuck", "Straddle Front Lever"],
    description: "Elite calisthenics skill requiring extraordinary back and core strength.",
    instructions: [
      "Hang from pull-up bar",
      "Pull body up to horizontal face-up",
      "Keep body rigid in a straight line",
      "Maintain full arm extension",
      "Hold position for desired time",
    ],
    caloriesPerRep: 2.0,
    repDuration: 10,
    met_value: 8.0,
    icon: "body-outline",
    color: "#A855F7",
  },
  {
    id: "planche",
    name: "Planche Hold",
    category: "calisthenics",
    subcategory: "Skills",
    equipment: ["none"],
    movement_pattern: "hold",
    muscle_groups: ["Anterior Deltoid", "Chest", "Triceps", "Core"],
    targetMuscles: ["Anterior Deltoid", "Chest", "Triceps"],
    difficulty: "advanced",
    is_compound: true,
    variations: ["Tuck Planche", "Straddle Planche", "Full Planche"],
    description: "The ultimate calisthenics pressing skill. Body horizontal parallel to ground.",
    instructions: [
      "Place hands on floor, fingers pointing backward",
      "Lean forward until shoulders pass hands",
      "Protract shoulders and lift feet",
      "Hold body horizontal with straight arms",
      "Maintain full body tension",
    ],
    caloriesPerRep: 2.5,
    repDuration: 10,
    met_value: 9.0,
    icon: "body-outline",
    color: "#A855F7",
  },
  {
    id: "handstand_pushup",
    name: "Handstand Push-up",
    category: "calisthenics",
    subcategory: "Skills",
    equipment: ["none"],
    movement_pattern: "push",
    muscle_groups: ["Anterior Deltoid", "Triceps", "Upper Traps"],
    targetMuscles: ["Shoulders", "Triceps"],
    difficulty: "advanced",
    is_compound: true,
    variations: ["Wall Handstand Push-up", "Pike Push-up", "Strict HSPU"],
    description: "Inverted pressing movement building superhuman shoulder strength.",
    instructions: [
      "Kick up into handstand against wall",
      "Position hands shoulder-width apart",
      "Lower head to floor in controlled motion",
      "Press back up explosively",
      "Maintain rigid body tension",
    ],
    caloriesPerRep: 1.0,
    repDuration: 5,
    met_value: 7.0,
    icon: "body-outline",
    color: "#A855F7",
  },

  // ─────────────────── MARTIAL ARTS ───────────────────
  {
    id: "jab_cross",
    name: "Jab-Cross Combo",
    category: "martial_arts",
    subcategory: "Boxing",
    equipment: ["none"],
    movement_pattern: "strike",
    muscle_groups: ["Shoulders", "Chest", "Core", "Legs"],
    targetMuscles: ["Shoulders", "Core", "Chest"],
    difficulty: "beginner",
    is_compound: true,
    variations: ["Double Jab", "Jab-Cross-Hook", "Southpaw Jab-Cross"],
    description: "The foundational two-punch combination of boxing. Builds speed and coordination.",
    instructions: [
      "Stand in boxing stance, non-dominant foot forward",
      "Throw a quick jab with lead hand",
      "Follow immediately with a powerful cross",
      "Rotate hips for power on the cross",
      "Return hands to guard position",
    ],
    caloriesPerRep: 0.6,
    repDuration: 2,
    met_value: 7.5,
    icon: "fitness-outline",
    color: "#EF4444",
  },
  {
    id: "hook_uppercut",
    name: "Hook-Uppercut Combo",
    category: "martial_arts",
    subcategory: "Boxing",
    equipment: ["none"],
    movement_pattern: "strike",
    muscle_groups: ["Core", "Shoulders", "Biceps", "Obliques"],
    targetMuscles: ["Core", "Shoulders", "Obliques"],
    difficulty: "intermediate",
    is_compound: true,
    variations: ["Double Hook", "Body Hook", "Lead Uppercut"],
    description: "Power combination targeting the body and head. Essential for inside fighting.",
    instructions: [
      "Start from boxing stance",
      "Throw lead hook rotating hip",
      "Follow with rear uppercut",
      "Drive power from legs upward",
      "Return to guard",
    ],
    caloriesPerRep: 0.7,
    repDuration: 2,
    met_value: 8.0,
    icon: "fitness-outline",
    color: "#EF4444",
  },
  {
    id: "roundhouse_kick",
    name: "Roundhouse Kick",
    category: "martial_arts",
    subcategory: "Kickboxing",
    equipment: ["none"],
    movement_pattern: "strike",
    muscle_groups: ["Hip Flexors", "Glutes", "Quads", "Core"],
    targetMuscles: ["Hip Flexors", "Glutes", "Core"],
    difficulty: "intermediate",
    is_compound: true,
    variations: ["Low Kick", "High Kick", "Spinning Heel Kick"],
    description: "The signature kick of Muay Thai and kickboxing. Devastating power weapon.",
    instructions: [
      "Stand in fighting stance",
      "Pivot on lead foot as you chamber rear knee",
      "Extend leg and rotate hip forward",
      "Strike with the shin bone",
      "Return foot to stance position",
    ],
    caloriesPerRep: 0.8,
    repDuration: 2,
    met_value: 9.0,
    icon: "fitness-outline",
    color: "#EF4444",
  },
  {
    id: "shadow_boxing",
    name: "Shadow Boxing",
    category: "martial_arts",
    subcategory: "Conditioning",
    equipment: ["none"],
    movement_pattern: "strike",
    muscle_groups: ["Full Body", "Core", "Shoulders", "Legs"],
    targetMuscles: ["Core", "Shoulders", "Legs"],
    difficulty: "beginner",
    is_compound: true,
    variations: ["Shadow Kickboxing", "Shadow MMA", "Visualization Boxing"],
    description: "Free-form fighting practice against an imaginary opponent. Builds technique and cardio.",
    instructions: [
      "Stand in boxing or fighting stance",
      "Move around as if facing an opponent",
      "Mix punches, kicks, and footwork",
      "Focus on technique over speed",
      "Keep hands up in guard position",
    ],
    caloriesPerRep: 0.5,
    repDuration: 60,
    met_value: 7.0,
    icon: "fitness-outline",
    color: "#EF4444",
  },
  {
    id: "front_kick",
    name: "Front Kick",
    category: "martial_arts",
    subcategory: "Kickboxing",
    equipment: ["none"],
    movement_pattern: "strike",
    muscle_groups: ["Quads", "Hip Flexors", "Core"],
    targetMuscles: ["Quads", "Hip Flexors", "Core"],
    difficulty: "beginner",
    is_compound: false,
    variations: ["Push Kick", "Teep", "Snap Front Kick"],
    description: "Linear kick that creates distance and scores. Essential in Muay Thai as the teep.",
    instructions: [
      "Stand in fighting stance",
      "Chamber the knee toward chest",
      "Extend leg forward powerfully",
      "Strike with ball or heel of foot",
      "Return leg and reset stance",
    ],
    caloriesPerRep: 0.6,
    repDuration: 2,
    met_value: 7.0,
    icon: "fitness-outline",
    color: "#EF4444",
  },
  {
    id: "sprawl_drill",
    name: "Sprawl Drill",
    category: "martial_arts",
    subcategory: "Wrestling",
    equipment: ["mat"],
    movement_pattern: "squat",
    muscle_groups: ["Core", "Hip Flexors", "Glutes", "Shoulders"],
    targetMuscles: ["Core", "Hip Flexors", "Glutes"],
    difficulty: "intermediate",
    is_compound: true,
    variations: ["Sprawl and Spin", "Counter Takedown"],
    description: "Explosive defensive movement to prevent takedowns in wrestling and MMA.",
    instructions: [
      "Stand in fighting stance",
      "Drive hips down to the mat explosively",
      "Shoot legs back simultaneously",
      "Land with weight on hands and hips",
      "Pop back up to fighting stance",
    ],
    caloriesPerRep: 0.9,
    repDuration: 2,
    met_value: 10.0,
    icon: "fitness-outline",
    color: "#EF4444",
  },
  {
    id: "bob_weave",
    name: "Bob and Weave",
    category: "martial_arts",
    subcategory: "Boxing",
    equipment: ["none"],
    movement_pattern: "squat",
    muscle_groups: ["Core", "Legs", "Neck", "Shoulders"],
    targetMuscles: ["Core", "Legs", "Neck"],
    difficulty: "beginner",
    is_compound: true,
    variations: ["Slip Drill", "U-Roll", "Defense Ladder"],
    description: "Head movement pattern to evade punches while setting up counters.",
    instructions: [
      "Stand in boxing stance",
      "Dip head to one side by bending knees",
      "Roll under imaginary punch",
      "Rise on the other side",
      "Return punches from this new angle",
    ],
    caloriesPerRep: 0.4,
    repDuration: 2,
    met_value: 6.0,
    icon: "fitness-outline",
    color: "#EF4444",
  },

  // ─────────────────── YOGA ───────────────────
  {
    id: "downward_dog",
    name: "Downward Dog",
    category: "yoga",
    subcategory: "Foundation",
    equipment: ["mat"],
    movement_pattern: "mobility",
    muscle_groups: ["Hamstrings", "Calves", "Shoulders", "Upper Back"],
    targetMuscles: ["Hamstrings", "Calves", "Shoulders"],
    difficulty: "beginner",
    is_compound: true,
    variations: ["Three-Legged Dog", "Downward Dog Twist", "Puppy Pose"],
    description: "An iconic yoga pose that stretches the entire posterior chain and strengthens the arms.",
    instructions: [
      "Start on hands and knees",
      "Tuck toes and lift hips toward ceiling",
      "Straighten arms and legs",
      "Press heels toward the floor",
      "Hold for 5 breaths",
    ],
    caloriesPerRep: 0.1,
    repDuration: 30,
    met_value: 2.5,
    icon: "leaf-outline",
    color: "#10B981",
  },
  {
    id: "warrior_one",
    name: "Warrior I",
    category: "yoga",
    subcategory: "Standing",
    equipment: ["mat"],
    movement_pattern: "squat",
    muscle_groups: ["Quads", "Hip Flexors", "Shoulders", "Core"],
    targetMuscles: ["Quads", "Hip Flexors", "Shoulders"],
    difficulty: "beginner",
    is_compound: true,
    variations: ["Warrior II", "Warrior III", "Humble Warrior"],
    description: "Powerful standing pose building strength, balance, and hip flexibility.",
    instructions: [
      "Step right foot back 4 feet",
      "Turn back foot out 45 degrees",
      "Bend front knee to 90 degrees",
      "Raise arms overhead and look up",
      "Hold for 5 breaths each side",
    ],
    caloriesPerRep: 0.12,
    repDuration: 30,
    met_value: 2.5,
    icon: "leaf-outline",
    color: "#10B981",
  },
  {
    id: "warrior_two",
    name: "Warrior II",
    category: "yoga",
    subcategory: "Standing",
    equipment: ["mat"],
    movement_pattern: "squat",
    muscle_groups: ["Quads", "Inner Thighs", "Shoulders", "Core"],
    targetMuscles: ["Quads", "Inner Thighs", "Shoulders"],
    difficulty: "beginner",
    is_compound: true,
    variations: ["Reverse Warrior", "Extended Side Angle"],
    description: "Expansive standing pose that opens the hips and builds endurance.",
    instructions: [
      "Stand with feet wide apart",
      "Turn front foot 90 degrees",
      "Bend front knee over ankle",
      "Extend arms parallel to floor",
      "Gaze over front hand",
    ],
    caloriesPerRep: 0.12,
    repDuration: 30,
    met_value: 2.5,
    icon: "leaf-outline",
    color: "#10B981",
  },
  {
    id: "tree_pose",
    name: "Tree Pose",
    category: "yoga",
    subcategory: "Balance",
    equipment: ["mat"],
    movement_pattern: "balance",
    muscle_groups: ["Core", "Inner Thighs", "Glutes", "Calves"],
    targetMuscles: ["Core", "Inner Thighs"],
    difficulty: "beginner",
    is_compound: false,
    variations: ["Eagle Pose", "Half Moon Pose"],
    description: "Single-leg balance pose that improves focus, balance, and ankle stability.",
    instructions: [
      "Stand on one foot",
      "Place other foot on inner calf or thigh",
      "Bring hands to prayer at chest",
      "Fix gaze on a steady point",
      "Hold 30-60 seconds each side",
    ],
    caloriesPerRep: 0.08,
    repDuration: 30,
    met_value: 2.0,
    icon: "leaf-outline",
    color: "#10B981",
  },
  {
    id: "pigeon_pose",
    name: "Pigeon Pose",
    category: "yoga",
    subcategory: "Hip Opening",
    equipment: ["mat"],
    movement_pattern: "mobility",
    muscle_groups: ["Hip Flexors", "Glutes", "Piriformis", "Psoas"],
    targetMuscles: ["Hip Flexors", "Glutes", "Piriformis"],
    difficulty: "intermediate",
    is_compound: false,
    variations: ["Double Pigeon", "Sleeping Pigeon", "King Pigeon"],
    description: "Deep hip opener that targets the external rotators and hip flexors.",
    instructions: [
      "Start from downward dog",
      "Bring right knee to right wrist",
      "Lower hips toward floor",
      "Extend back leg straight behind",
      "Fold forward and hold",
    ],
    caloriesPerRep: 0.1,
    repDuration: 60,
    met_value: 2.5,
    icon: "leaf-outline",
    color: "#10B981",
  },
  {
    id: "sun_salutation",
    name: "Sun Salutation",
    category: "yoga",
    subcategory: "Flow",
    equipment: ["mat"],
    movement_pattern: "mobility",
    muscle_groups: ["Full Body", "Core", "Shoulders", "Hamstrings"],
    targetMuscles: ["Full Body", "Core", "Hamstrings"],
    difficulty: "beginner",
    is_compound: true,
    variations: ["Sun Salutation B", "Half Sun Salutation"],
    description: "A sequence of 12 yoga poses flowing together. The perfect full-body warm-up.",
    instructions: [
      "Begin in Mountain Pose (Tadasana)",
      "Flow through raised arms, forward fold",
      "Step back to plank, lower to floor",
      "Cobra or upward dog on inhale",
      "Downward dog, then return to start",
    ],
    caloriesPerRep: 0.5,
    repDuration: 60,
    met_value: 3.5,
    icon: "leaf-outline",
    color: "#10B981",
  },
  {
    id: "boat_pose",
    name: "Boat Pose",
    category: "yoga",
    subcategory: "Core",
    equipment: ["mat"],
    movement_pattern: "hold",
    muscle_groups: ["Abs", "Hip Flexors", "Lower Back"],
    targetMuscles: ["Abs", "Hip Flexors"],
    difficulty: "intermediate",
    is_compound: false,
    variations: ["Low Boat", "Boat with Twist", "Half Boat"],
    description: "Core-intensive yoga pose that challenges stability and builds abdominal strength.",
    instructions: [
      "Sit with knees bent, feet flat",
      "Lean back to 45 degrees",
      "Lift feet to knee height",
      "Extend arms forward parallel to floor",
      "Hold and breathe steadily",
    ],
    caloriesPerRep: 0.15,
    repDuration: 30,
    met_value: 3.0,
    icon: "leaf-outline",
    color: "#10B981",
  },

  // ─────────────────── CARDIO ───────────────────
  {
    id: "jumping_jacks",
    name: "Jumping Jacks",
    category: "cardio",
    subcategory: "Full Body Cardio",
    equipment: ["none"],
    movement_pattern: "cardio",
    muscle_groups: ["Full Body", "Calves", "Shoulders", "Core"],
    targetMuscles: ["Full Body", "Calves", "Shoulders"],
    difficulty: "beginner",
    is_compound: true,
    variations: ["Seal Jacks", "Half Jack", "Star Jump"],
    description: "Classic full-body cardio exercise that elevates heart rate quickly.",
    instructions: [
      "Stand with feet together, arms at sides",
      "Jump feet apart while raising arms overhead",
      "Jump back to starting position",
      "Maintain a steady, rhythmic pace",
      "Land softly with knees slightly bent",
    ],
    caloriesPerRep: 0.3,
    repDuration: 1,
    met_value: 8.0,
    icon: "flash-outline",
    color: "#06B6D4",
  },
  {
    id: "burpee",
    name: "Burpee",
    category: "cardio",
    subcategory: "HIIT",
    equipment: ["none"],
    movement_pattern: "cardio",
    muscle_groups: ["Full Body", "Chest", "Quads", "Shoulders", "Core"],
    targetMuscles: ["Full Body", "Chest", "Quads"],
    difficulty: "intermediate",
    is_compound: true,
    variations: ["Half Burpee", "Burpee with Push-up", "Box Jump Burpee"],
    description: "The ultimate full-body conditioning exercise. High calorie burn and total body challenge.",
    instructions: [
      "Stand with feet shoulder-width apart",
      "Drop into a squat, hands to floor",
      "Jump feet back to plank position",
      "Do a push-up (optional)",
      "Jump feet to hands, then explode up",
    ],
    caloriesPerRep: 1.0,
    repDuration: 3,
    met_value: 10.0,
    icon: "flash-outline",
    color: "#06B6D4",
  },
  {
    id: "high_knees",
    name: "High Knees",
    category: "cardio",
    subcategory: "Running-Based",
    equipment: ["none"],
    movement_pattern: "cardio",
    muscle_groups: ["Quads", "Hip Flexors", "Core", "Calves"],
    targetMuscles: ["Quads", "Hip Flexors", "Core"],
    difficulty: "beginner",
    is_compound: true,
    variations: ["High Knee March", "High Knee Skip"],
    description: "Running-in-place drill that elevates heart rate and improves hip flexor strength.",
    instructions: [
      "Stand with feet hip-width apart",
      "Drive right knee up to hip height",
      "Quickly switch to left knee",
      "Pump arms in opposition",
      "Maintain quick cadence",
    ],
    caloriesPerRep: 0.25,
    repDuration: 1,
    met_value: 8.5,
    icon: "flash-outline",
    color: "#06B6D4",
  },
  {
    id: "mountain_climbers",
    name: "Mountain Climbers",
    category: "cardio",
    subcategory: "HIIT",
    equipment: ["none"],
    movement_pattern: "cardio",
    muscle_groups: ["Core", "Quads", "Hip Flexors", "Shoulders"],
    targetMuscles: ["Core", "Quads", "Hip Flexors"],
    difficulty: "beginner",
    is_compound: true,
    variations: ["Slow Mountain Climbers", "Cross-Body Mountain Climbers"],
    description: "Dynamic plank-based exercise combining core strength with cardio conditioning.",
    instructions: [
      "Start in a high plank position",
      "Drive right knee toward chest",
      "Quickly switch to left knee",
      "Keep hips level throughout",
      "Maintain quick alternating pace",
    ],
    caloriesPerRep: 0.3,
    repDuration: 1,
    met_value: 8.0,
    icon: "flash-outline",
    color: "#06B6D4",
  },
  {
    id: "box_jump",
    name: "Box Jump",
    category: "cardio",
    subcategory: "Plyometrics",
    equipment: ["none"],
    movement_pattern: "squat",
    muscle_groups: ["Quads", "Glutes", "Calves", "Core"],
    targetMuscles: ["Quads", "Glutes", "Calves"],
    difficulty: "intermediate",
    is_compound: true,
    variations: ["Lateral Box Jump", "Step-Down Box Jump", "Single Leg Box Jump"],
    description: "Plyometric exercise that builds explosive leg power and athletic performance.",
    instructions: [
      "Stand in front of a sturdy box",
      "Swing arms back and bend knees",
      "Explode upward swinging arms forward",
      "Land softly on the box in squat position",
      "Step down carefully and repeat",
    ],
    caloriesPerRep: 0.9,
    repDuration: 3,
    met_value: 9.0,
    icon: "flash-outline",
    color: "#06B6D4",
  },
  {
    id: "speed_skaters",
    name: "Speed Skaters",
    category: "cardio",
    subcategory: "Lateral Cardio",
    equipment: ["none"],
    movement_pattern: "cardio",
    muscle_groups: ["Glutes", "Inner Thighs", "Core", "Calves"],
    targetMuscles: ["Glutes", "Inner Thighs", "Core"],
    difficulty: "intermediate",
    is_compound: true,
    variations: ["Slow Skater", "Skater with Touch"],
    description: "Lateral movement pattern mimicking speed skaters. Excellent for glutes and cardio.",
    instructions: [
      "Stand on right foot",
      "Leap to the left landing on left foot",
      "Swing right leg behind you",
      "Immediately leap to the right",
      "Build speed with continuous rhythm",
    ],
    caloriesPerRep: 0.4,
    repDuration: 2,
    met_value: 8.0,
    icon: "flash-outline",
    color: "#06B6D4",
  },
  {
    id: "jump_rope",
    name: "Jump Rope",
    category: "cardio",
    subcategory: "Rope Cardio",
    equipment: ["rope"],
    movement_pattern: "cardio",
    muscle_groups: ["Calves", "Shoulders", "Core", "Wrists"],
    targetMuscles: ["Calves", "Shoulders", "Core"],
    difficulty: "beginner",
    is_compound: true,
    variations: ["Double Under", "Alternating Foot", "Cross-Jump"],
    description: "One of the most efficient cardiovascular exercises. Improves coordination and endurance.",
    instructions: [
      "Hold rope handles at hip height",
      "Jump with feet together or alternating",
      "Rotate rope with wrists not arms",
      "Stay on balls of feet",
      "Build up speed gradually",
    ],
    caloriesPerRep: 0.35,
    repDuration: 1,
    met_value: 10.0,
    icon: "flash-outline",
    color: "#06B6D4",
  },

  // ─────────────────── REHAB / BALANCE ───────────────────
  {
    id: "glute_bridge",
    name: "Glute Bridge",
    category: "rehab",
    subcategory: "Glute Activation",
    equipment: ["mat"],
    movement_pattern: "hinge",
    muscle_groups: ["Glutes", "Hamstrings", "Lower Back", "Core"],
    targetMuscles: ["Glutes", "Hamstrings", "Lower Back"],
    difficulty: "beginner",
    is_compound: false,
    variations: ["Single Leg Glute Bridge", "Banded Glute Bridge", "Hip Thrust"],
    description: "Foundational glute activation exercise essential for injury prevention and posture.",
    instructions: [
      "Lie on back with knees bent, feet flat",
      "Place arms at sides",
      "Drive hips up by squeezing glutes",
      "Hold at top for 2 seconds",
      "Lower hips slowly and repeat",
    ],
    caloriesPerRep: 0.25,
    repDuration: 3,
    met_value: 3.0,
    icon: "shield-checkmark-outline",
    color: "#8B5CF6",
  },
  {
    id: "bird_dog",
    name: "Bird Dog",
    category: "rehab",
    subcategory: "Core Stability",
    equipment: ["mat"],
    movement_pattern: "balance",
    muscle_groups: ["Core", "Glutes", "Lower Back", "Shoulders"],
    targetMuscles: ["Core", "Lower Back", "Glutes"],
    difficulty: "beginner",
    is_compound: true,
    variations: ["Bird Dog Crunch", "Weighted Bird Dog"],
    description: "Quadruped stability exercise that trains core coordination and spinal stability.",
    instructions: [
      "Start on hands and knees",
      "Extend right arm and left leg simultaneously",
      "Keep back flat and hips level",
      "Hold for 2 seconds",
      "Return and switch sides",
    ],
    caloriesPerRep: 0.2,
    repDuration: 4,
    met_value: 2.5,
    icon: "shield-checkmark-outline",
    color: "#8B5CF6",
  },
  {
    id: "dead_bug",
    name: "Dead Bug",
    category: "rehab",
    subcategory: "Core Stability",
    equipment: ["mat"],
    movement_pattern: "hold",
    muscle_groups: ["Abs", "Hip Flexors", "Core", "Transverse Abdominis"],
    targetMuscles: ["Abs", "Core", "Transverse Abdominis"],
    difficulty: "beginner",
    is_compound: true,
    variations: ["Single Arm Dead Bug", "Leg Extension Dead Bug"],
    description: "Anti-extension core exercise that protects the lumbar spine.",
    instructions: [
      "Lie on back with arms pointed to ceiling",
      "Bend knees to 90 degrees, feet in air",
      "Lower opposite arm and leg slowly",
      "Keep lower back pressed to floor",
      "Return and alternate sides",
    ],
    caloriesPerRep: 0.2,
    repDuration: 4,
    met_value: 2.5,
    icon: "shield-checkmark-outline",
    color: "#8B5CF6",
  },
  {
    id: "clamshell",
    name: "Clamshell",
    category: "rehab",
    subcategory: "Hip Activation",
    equipment: ["mat"],
    movement_pattern: "mobility",
    muscle_groups: ["Glutes", "Hip External Rotators", "TFL"],
    targetMuscles: ["Glutes", "Hip External Rotators"],
    difficulty: "beginner",
    is_compound: false,
    variations: ["Banded Clamshell", "Clamshell with Hip Lift"],
    description: "Hip abductor exercise that activates the glute med and prevents knee pain.",
    instructions: [
      "Lie on side with knees stacked at 45 degrees",
      "Keep feet together",
      "Rotate top knee upward like a clamshell",
      "Do not rotate pelvis",
      "Squeeze glute at top",
    ],
    caloriesPerRep: 0.15,
    repDuration: 3,
    met_value: 2.0,
    icon: "shield-checkmark-outline",
    color: "#8B5CF6",
  },
  {
    id: "single_leg_balance",
    name: "Single Leg Balance",
    category: "rehab",
    subcategory: "Balance Training",
    equipment: ["none"],
    movement_pattern: "balance",
    muscle_groups: ["Ankle Stabilizers", "Core", "Glutes", "Quads"],
    targetMuscles: ["Ankle Stabilizers", "Core", "Glutes"],
    difficulty: "beginner",
    is_compound: false,
    variations: ["Eyes Closed Balance", "Balance with Arm Reach", "Wobble Board"],
    description: "Fundamental balance exercise for ankle stability and injury prevention.",
    instructions: [
      "Stand on one foot",
      "Keep slight bend in standing knee",
      "Focus on a fixed point for balance",
      "Hold 30-60 seconds",
      "Challenge by closing eyes or reaching",
    ],
    caloriesPerRep: 0.05,
    repDuration: 30,
    met_value: 2.0,
    icon: "shield-checkmark-outline",
    color: "#8B5CF6",
  },
  {
    id: "thoracic_rotation",
    name: "Thoracic Rotation",
    category: "rehab",
    subcategory: "Mobility",
    equipment: ["mat"],
    movement_pattern: "rotation",
    muscle_groups: ["Thoracic Spine", "Obliques", "Rotator Cuff"],
    targetMuscles: ["Thoracic Spine", "Obliques"],
    difficulty: "beginner",
    is_compound: false,
    variations: ["Quadruped Thoracic Rotation", "Side-Lying Thoracic Rotation"],
    description: "Mobility drill to restore thoracic rotation, essential for shoulder and back health.",
    instructions: [
      "Lie on side in fetal position",
      "Place hands together in front",
      "Open top arm rotating thorax",
      "Follow with your gaze",
      "Return and repeat",
    ],
    caloriesPerRep: 0.1,
    repDuration: 5,
    met_value: 2.0,
    icon: "shield-checkmark-outline",
    color: "#8B5CF6",
  },
  {
    id: "hip_flexor_stretch",
    name: "Hip Flexor Lunge Stretch",
    category: "rehab",
    subcategory: "Flexibility",
    equipment: ["mat"],
    movement_pattern: "mobility",
    muscle_groups: ["Hip Flexors", "Psoas", "Quad", "Groin"],
    targetMuscles: ["Hip Flexors", "Psoas"],
    difficulty: "beginner",
    is_compound: false,
    variations: ["Kneeling Lunge", "Dynamic Hip Flexor Stretch"],
    description: "Counteracts the effects of prolonged sitting. Essential stretch for desk workers.",
    instructions: [
      "Kneel on one knee, foot in front",
      "Push hips forward gently",
      "Keep torso upright and tall",
      "Hold for 30-60 seconds",
      "Switch legs and repeat",
    ],
    caloriesPerRep: 0.05,
    repDuration: 30,
    met_value: 1.5,
    icon: "shield-checkmark-outline",
    color: "#8B5CF6",
  },
];

export const getExercisesByCategory = (category: ExerciseCategory): ExerciseGroup[] => {
  const filtered = EXERCISES.filter(e => e.category === category);
  const groups: Record<string, Exercise[]> = {};
  filtered.forEach(e => {
    if (!groups[e.subcategory]) groups[e.subcategory] = [];
    groups[e.subcategory].push(e);
  });
  return Object.entries(groups).map(([subcategory, exercises]) => ({ subcategory, exercises }));
};

export const getCategoryColor = (category: ExerciseCategory): string => {
  const map: Record<ExerciseCategory, string> = {
    freehand: "#00FF88",
    gym: "#FF6B35",
    calisthenics: "#A855F7",
    martial_arts: "#EF4444",
    yoga: "#10B981",
    cardio: "#06B6D4",
    rehab: "#8B5CF6",
  };
  return map[category] ?? "#00FF88";
};

export const getCategoryIcon = (category: ExerciseCategory): string => {
  const map: Record<ExerciseCategory, string> = {
    freehand: "body-outline",
    gym: "barbell-outline",
    calisthenics: "fitness-outline",
    martial_arts: "flame-outline",
    yoga: "leaf-outline",
    cardio: "flash-outline",
    rehab: "shield-checkmark-outline",
  };
  return map[category] ?? "body-outline";
};

export const getCategoryLabel = (category: ExerciseCategory): string => {
  const map: Record<ExerciseCategory, string> = {
    freehand: "Bodyweight",
    gym: "Gym",
    calisthenics: "Calisthenics",
    martial_arts: "Martial Arts",
    yoga: "Yoga",
    cardio: "Cardio",
    rehab: "Rehab",
  };
  return map[category] ?? category;
};
